/* File: blassmmodule.c
 * This file is auto-generated with f2py (version:2_5237).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct 27 11:51:19 2009
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *blassm_error;
static PyObject *blassm_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = blassm_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = blassm_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(amub,AMUB)(int*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,int*,int*,int*);
extern void F_FUNC(aplsb,APLSB)(int*,int*,double*,int*,int*,double*,double*,int*,int*,double*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ amub ************************************/
static char doc_f2py_rout_blassm_amub[] = "\
Function signature:\n\
  c,jc,ic,ierr = amub(ncol,a,ja,ia,b,jb,ib,nzmax,[job])\n\
Required arguments:\n"
"  ncol : input int\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  b : input rank-1 array('d') with bounds (*)\n"
"  jb : input rank-1 array('i') with bounds (*)\n"
"  ib : input rank-1 array('i') with bounds (*)\n"
"  nzmax : input int\n"
"Optional arguments:\n"
"  job := 1 input int\n"
"Return objects:\n"
"  c : rank-1 array('d') with bounds (nzmax)\n"
"  jc : rank-1 array('i') with bounds (nzmax)\n"
"  ic : rank-1 array('i') with bounds (nrow + 1)\n"
"  ierr : int";
/* extern void F_FUNC(amub,AMUB)(int*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_blassm_amub(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,int*,int*,double*,int*,int*,double*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nrow = 0;
  int ncol = 0;
  PyObject *ncol_capi = Py_None;
  int job = 0;
  PyObject *job_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int *jb = NULL;
  npy_intp jb_Dims[1] = {-1};
  const int jb_Rank = 1;
  PyArrayObject *capi_jb_tmp = NULL;
  int capi_jb_intent = 0;
  PyObject *jb_capi = Py_None;
  int *ib = NULL;
  npy_intp ib_Dims[1] = {-1};
  const int ib_Rank = 1;
  PyArrayObject *capi_ib_tmp = NULL;
  int capi_ib_intent = 0;
  PyObject *ib_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[1] = {-1};
  const int c_Rank = 1;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  int *jc = NULL;
  npy_intp jc_Dims[1] = {-1};
  const int jc_Rank = 1;
  PyArrayObject *capi_jc_tmp = NULL;
  int capi_jc_intent = 0;
  int *ic = NULL;
  npy_intp ic_Dims[1] = {-1};
  const int ic_Rank = 1;
  PyArrayObject *capi_ic_tmp = NULL;
  int capi_ic_intent = 0;
  int nzmax = 0;
  PyObject *nzmax_capi = Py_None;
  int *iw = NULL;
  npy_intp iw_Dims[1] = {-1};
  const int iw_Rank = 1;
  PyArrayObject *capi_iw_tmp = NULL;
  int capi_iw_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"ncol","a","ja","ia","b","jb","ib","nzmax","job",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO|O:blassm.amub",\
    capi_kwlist,&ncol_capi,&a_capi,&ja_capi,&ia_capi,&b_capi,&jb_capi,&ib_capi,&nzmax_capi,&job_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 2nd argument `a' of blassm.amub to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(PyArray_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 5th argument `b' of blassm.amub to C/Fortran array" );
  } else {
    b = (double *)(capi_b_tmp->data);

  /* Processing variable ierr */
  /* Processing variable job */
  if (job_capi == Py_None) job = 1; else
    f2py_success = int_from_pyobj(&job,job_capi,"blassm.amub() 1st keyword (job) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nzmax */
    f2py_success = int_from_pyobj(&nzmax,nzmax_capi,"blassm.amub() 8th argument (nzmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ncol */
    f2py_success = int_from_pyobj(&ncol,ncol_capi,"blassm.amub() 1st argument (ncol) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 4th argument `ia' of blassm.amub to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ib */
  ;
  capi_ib_intent |= F2PY_INTENT_IN;
  capi_ib_tmp = array_from_pyobj(PyArray_INT,ib_Dims,ib_Rank,capi_ib_intent,ib_capi);
  if (capi_ib_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 7th argument `ib' of blassm.amub to C/Fortran array" );
  } else {
    ib = (int *)(capi_ib_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 3rd argument `ja' of blassm.amub to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jb */
  ;
  capi_jb_intent |= F2PY_INTENT_IN;
  capi_jb_tmp = array_from_pyobj(PyArray_INT,jb_Dims,jb_Rank,capi_jb_intent,jb_capi);
  if (capi_jb_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 6th argument `jb' of blassm.amub to C/Fortran array" );
  } else {
    jb = (int *)(capi_jb_tmp->data);

  /* Processing variable c */
  c_Dims[0]=nzmax;
  capi_c_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_c_tmp = array_from_pyobj(PyArray_DOUBLE,c_Dims,c_Rank,capi_c_intent,Py_None);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `c' of blassm.amub to C/Fortran array" );
  } else {
    c = (double *)(capi_c_tmp->data);

  /* Processing variable nrow */
  nrow = len(ia)-1;
  /* Processing variable iw */
  iw_Dims[0]=ncol;
  capi_iw_intent |= F2PY_INTENT_HIDE;
  capi_iw_tmp = array_from_pyobj(PyArray_INT,iw_Dims,iw_Rank,capi_iw_intent,Py_None);
  if (capi_iw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `iw' of blassm.amub to C/Fortran array" );
  } else {
    iw = (int *)(capi_iw_tmp->data);

  /* Processing variable ic */
  ic_Dims[0]=nrow + 1;
  capi_ic_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ic_tmp = array_from_pyobj(PyArray_INT,ic_Dims,ic_Rank,capi_ic_intent,Py_None);
  if (capi_ic_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `ic' of blassm.amub to C/Fortran array" );
  } else {
    ic = (int *)(capi_ic_tmp->data);

  /* Processing variable jc */
  jc_Dims[0]=nzmax;
  capi_jc_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jc_tmp = array_from_pyobj(PyArray_INT,jc_Dims,jc_Rank,capi_jc_intent,Py_None);
  if (capi_jc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `jc' of blassm.amub to C/Fortran array" );
  } else {
    jc = (int *)(capi_jc_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nrow,&ncol,&job,a,ja,ia,b,jb,ib,c,jc,ic,&nzmax,iw,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_c_tmp,capi_jc_tmp,capi_ic_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_jc_tmp == NULL) ... else of jc*/
  /* End of cleaning variable jc */
  }  /*if (capi_ic_tmp == NULL) ... else of ic*/
  /* End of cleaning variable ic */
    Py_XDECREF(capi_iw_tmp);
  }  /*if (capi_iw_tmp == NULL) ... else of iw*/
  /* End of cleaning variable iw */
  /* End of cleaning variable nrow */
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  if((PyObject *)capi_jb_tmp!=jb_capi) {
    Py_XDECREF(capi_jb_tmp); }
  }  /*if (capi_jb_tmp == NULL) ... else of jb*/
  /* End of cleaning variable jb */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ib_tmp!=ib_capi) {
    Py_XDECREF(capi_ib_tmp); }
  }  /*if (capi_ib_tmp == NULL) ... else of ib*/
  /* End of cleaning variable ib */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  } /*if (f2py_success) of ncol*/
  /* End of cleaning variable ncol */
  } /*if (f2py_success) of nzmax*/
  /* End of cleaning variable nzmax */
  } /*if (f2py_success) of job*/
  /* End of cleaning variable job */
  /* End of cleaning variable ierr */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of amub ********************************/

/*********************************** aplsb ***********************************/
static char doc_f2py_rout_blassm_aplsb[] = "\
Function signature:\n\
  c,jc,ic,ierr = aplsb(ncol,a,ja,ia,s,b,jb,ib,nzmax)\n\
Required arguments:\n"
"  ncol : input int\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  s : input float\n"
"  b : input rank-1 array('d') with bounds (*)\n"
"  jb : input rank-1 array('i') with bounds (*)\n"
"  ib : input rank-1 array('i') with bounds (len(ia))\n"
"  nzmax : input int\n"
"Return objects:\n"
"  c : rank-1 array('d') with bounds (nzmax)\n"
"  jc : rank-1 array('i') with bounds (nzmax)\n"
"  ic : rank-1 array('i') with bounds (len(ia))\n"
"  ierr : int";
/* extern void F_FUNC(aplsb,APLSB)(int*,int*,double*,int*,int*,double*,double*,int*,int*,double*,int*,int*,int*,int*); */
static PyObject *f2py_rout_blassm_aplsb(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,int*,int*,double*,double*,int*,int*,double*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nrow = 0;
  int ncol = 0;
  PyObject *ncol_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  double s = 0;
  PyObject *s_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[1] = {-1};
  const int b_Rank = 1;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int *jb = NULL;
  npy_intp jb_Dims[1] = {-1};
  const int jb_Rank = 1;
  PyArrayObject *capi_jb_tmp = NULL;
  int capi_jb_intent = 0;
  PyObject *jb_capi = Py_None;
  int *ib = NULL;
  npy_intp ib_Dims[1] = {-1};
  const int ib_Rank = 1;
  PyArrayObject *capi_ib_tmp = NULL;
  int capi_ib_intent = 0;
  PyObject *ib_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[1] = {-1};
  const int c_Rank = 1;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  int *jc = NULL;
  npy_intp jc_Dims[1] = {-1};
  const int jc_Rank = 1;
  PyArrayObject *capi_jc_tmp = NULL;
  int capi_jc_intent = 0;
  int *ic = NULL;
  npy_intp ic_Dims[1] = {-1};
  const int ic_Rank = 1;
  PyArrayObject *capi_ic_tmp = NULL;
  int capi_ic_intent = 0;
  int nzmax = 0;
  PyObject *nzmax_capi = Py_None;
  int ierr = 0;
  static char *capi_kwlist[] = {"ncol","a","ja","ia","s","b","jb","ib","nzmax",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|:blassm.aplsb",\
    capi_kwlist,&ncol_capi,&a_capi,&ja_capi,&ia_capi,&s_capi,&b_capi,&jb_capi,&ib_capi,&nzmax_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 2nd argument `a' of blassm.aplsb to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(PyArray_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 6th argument `b' of blassm.aplsb to C/Fortran array" );
  } else {
    b = (double *)(capi_b_tmp->data);

  /* Processing variable ierr */
  /* Processing variable s */
    f2py_success = double_from_pyobj(&s,s_capi,"blassm.aplsb() 5th argument (s) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nzmax */
    f2py_success = int_from_pyobj(&nzmax,nzmax_capi,"blassm.aplsb() 9th argument (nzmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ncol */
    f2py_success = int_from_pyobj(&ncol,ncol_capi,"blassm.aplsb() 1st argument (ncol) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 4th argument `ia' of blassm.aplsb to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 3rd argument `ja' of blassm.aplsb to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jb */
  ;
  capi_jb_intent |= F2PY_INTENT_IN;
  capi_jb_tmp = array_from_pyobj(PyArray_INT,jb_Dims,jb_Rank,capi_jb_intent,jb_capi);
  if (capi_jb_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 7th argument `jb' of blassm.aplsb to C/Fortran array" );
  } else {
    jb = (int *)(capi_jb_tmp->data);

  /* Processing variable c */
  c_Dims[0]=nzmax;
  capi_c_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_c_tmp = array_from_pyobj(PyArray_DOUBLE,c_Dims,c_Rank,capi_c_intent,Py_None);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `c' of blassm.aplsb to C/Fortran array" );
  } else {
    c = (double *)(capi_c_tmp->data);

  /* Processing variable nrow */
  nrow = len(ia)-1;
  /* Processing variable ic */
  ic_Dims[0]=len(ia);
  capi_ic_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ic_tmp = array_from_pyobj(PyArray_INT,ic_Dims,ic_Rank,capi_ic_intent,Py_None);
  if (capi_ic_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `ic' of blassm.aplsb to C/Fortran array" );
  } else {
    ic = (int *)(capi_ic_tmp->data);

  /* Processing variable ib */
  ib_Dims[0]=len(ia);
  capi_ib_intent |= F2PY_INTENT_IN;
  capi_ib_tmp = array_from_pyobj(PyArray_INT,ib_Dims,ib_Rank,capi_ib_intent,ib_capi);
  if (capi_ib_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting 8th argument `ib' of blassm.aplsb to C/Fortran array" );
  } else {
    ib = (int *)(capi_ib_tmp->data);

  /* Processing variable jc */
  jc_Dims[0]=nzmax;
  capi_jc_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jc_tmp = array_from_pyobj(PyArray_INT,jc_Dims,jc_Rank,capi_jc_intent,Py_None);
  if (capi_jc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(blassm_error,"failed in converting hidden `jc' of blassm.aplsb to C/Fortran array" );
  } else {
    jc = (int *)(capi_jc_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&nrow,&ncol,a,ja,ia,&s,b,jb,ib,c,jc,ic,&nzmax,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_c_tmp,capi_jc_tmp,capi_ic_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_jc_tmp == NULL) ... else of jc*/
  /* End of cleaning variable jc */
  if((PyObject *)capi_ib_tmp!=ib_capi) {
    Py_XDECREF(capi_ib_tmp); }
  }  /*if (capi_ib_tmp == NULL) ... else of ib*/
  /* End of cleaning variable ib */
  }  /*if (capi_ic_tmp == NULL) ... else of ic*/
  /* End of cleaning variable ic */
  /* End of cleaning variable nrow */
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  if((PyObject *)capi_jb_tmp!=jb_capi) {
    Py_XDECREF(capi_jb_tmp); }
  }  /*if (capi_jb_tmp == NULL) ... else of jb*/
  /* End of cleaning variable jb */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  } /*if (f2py_success) of ncol*/
  /* End of cleaning variable ncol */
  } /*if (f2py_success) of nzmax*/
  /* End of cleaning variable nzmax */
  } /*if (f2py_success) of s*/
  /* End of cleaning variable s */
  /* End of cleaning variable ierr */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of aplsb ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"amub",-1,{{-1}},0,(char *)F_FUNC(amub,AMUB),(f2py_init_func)f2py_rout_blassm_amub,doc_f2py_rout_blassm_amub},
  {"aplsb",-1,{{-1}},0,(char *)F_FUNC(aplsb,APLSB),(f2py_init_func)f2py_rout_blassm_aplsb,doc_f2py_rout_blassm_aplsb},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initblassm(void) {
  int i;
  PyObject *m,*d, *s;
  m = blassm_module = Py_InitModule("blassm", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module blassm (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'blassm' is auto-generated with f2py (version:2_5237).\nFunctions:\n"
"  c,jc,ic,ierr = amub(ncol,a,ja,ia,b,jb,ib,nzmax,job=1)\n"
"  c,jc,ic,ierr = aplsb(ncol,a,ja,ia,s,b,jb,ib,nzmax)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  blassm_error = PyErr_NewException ("blassm.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"blassm");
#endif

}
#ifdef __cplusplus
}
#endif
