C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2_5237)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pywrapdbsval (dbsvalf2pywrap, x, kx, xknot, nx,
     & bcoef)
      external dbsval
      double precision x
      integer kx
      integer nx
      double precision xknot(nx+kx)
      double precision bcoef(nx)
      double precision dbsvalf2pywrap, dbsval
      dbsvalf2pywrap = dbsval(x, kx, xknot, nx, bcoef)
      end


      subroutine f2pywrapdbsder (dbsderf2pywrap, iderx, x, kx, xkn
     &ot, nx, bcoef)
      external dbsder
      integer iderx
      double precision x
      integer kx
      integer nx
      double precision xknot(nx+kx)
      double precision bcoef(nx)
      double precision dbsderf2pywrap, dbsder
      dbsderf2pywrap = dbsder(iderx, x, kx, xknot, nx, bcoef)
      end


      subroutine f2pywrapdbsdca (dbsdcaf2pywrap, iderx, x, kx, xkn
     &ot, nx, bcoef, leftx)
      external dbsdca
      integer iderx
      double precision x
      integer kx
      integer nx
      integer leftx
      double precision xknot(nx+kx)
      double precision bcoef(nx)
      double precision dbsdcaf2pywrap, dbsdca
      dbsdcaf2pywrap = dbsdca(iderx, x, kx, xknot, nx, bcoef, left
     &x)
      end


      subroutine f2pywrapdbs2vl (dbs2vlf2pywrap, x, y, kx, ky, xkn
     &ot, yknot, nx, ny, bcoef)
      external dbs2vl
      double precision x
      double precision y
      integer kx
      integer ky
      integer nx
      integer ny
      double precision xknot(nx+kx)
      double precision yknot(ny+ky)
      double precision bcoef(nx,ny)
      double precision dbs2vlf2pywrap, dbs2vl
      dbs2vlf2pywrap = dbs2vl(x, y, kx, ky, xknot, yknot, nx, ny, 
     &bcoef)
      end


      subroutine f2pywrapdbs2dr (dbs2drf2pywrap, iderx, idery, x, 
     &y, kx, ky, xknot, yknot, nx, ny, bcoef)
      external dbs2dr
      integer iderx
      integer idery
      double precision x
      double precision y
      integer kx
      integer ky
      integer nx
      integer ny
      double precision xknot(nx+kx)
      double precision yknot(ny+ky)
      double precision bcoef(nx,ny)
      double precision dbs2drf2pywrap, dbs2dr
      dbs2drf2pywrap = dbs2dr(iderx, idery, x, y, kx, ky, xknot, y
     &knot, nx, ny, bcoef)
      end


      subroutine f2pywrapdbs3vl (dbs3vlf2pywrap, x, y, z, kx, ky, 
     &kz, xknot, yknot, zknot, nx, ny, nz, bcoef)
      external dbs3vl
      double precision x
      double precision y
      double precision z
      integer kx
      integer ky
      integer kz
      integer nx
      integer ny
      integer nz
      double precision xknot(nx+kx)
      double precision yknot(ny+ky)
      double precision zknot(nz+kz)
      double precision bcoef(nx,ny,nz)
      double precision dbs3vlf2pywrap, dbs3vl
      dbs3vlf2pywrap = dbs3vl(x, y, z, kx, ky, kz, xknot, yknot, z
     &knot, nx, ny, nz, bcoef)
      end


      subroutine f2pywrapdbs3dr (dbs3drf2pywrap, iderx, idery, ide
     &rz, x, y, z, kx, ky, kz, xknot, yknot, zknot, nx, ny, nz, bcoef)
      external dbs3dr
      integer iderx
      integer idery
      integer iderz
      double precision x
      double precision y
      double precision z
      integer kx
      integer ky
      integer kz
      integer nx
      integer ny
      integer nz
      double precision xknot(nx+kx)
      double precision yknot(ny+ky)
      double precision zknot(nz+kz)
      double precision bcoef(nx,ny,nz)
      double precision dbs3drf2pywrap, dbs3dr
      dbs3drf2pywrap = dbs3dr(iderx, idery, iderz, x, y, z, kx, ky
     &, kz, xknot, yknot, zknot, nx, ny, nz, bcoef)
      end

