/* File: gelsymodule.c
 * This file is auto-generated with f2py (version:2_5237).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct 27 11:51:19 2009
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *gelsy_error;
static PyObject *gelsy_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef struct {float r,i;} complex_float;
typedef struct {double r,i;} complex_double;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    PyErr_SetString(gelsy_error,"("tcheck") failed for "name);\
    fprintf(stderr,show"\n",var);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define CHECKARRAY(check,tcheck,name) \
  if (!(check)) {\
    PyErr_SetString(gelsy_error,"("tcheck") failed for "name);\
    /*goto capi_fail;*/\
  } else 

/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = gelsy_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
  double d=0.0;
  if (double_from_pyobj(&d,obj,errmess)) {
    *v = (float)d;
    return 1;
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = gelsy_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(sgelsy,SGELSY)(int*,int*,int*,float*,int*,float*,int*,int*,float*,int*,float*,int*,int*);
extern void F_FUNC(dgelsy,DGELSY)(int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,double*,int*,int*);
extern void F_FUNC(cgelsy,CGELSY)(int*,int*,int*,complex_float*,int*,complex_float*,int*,int*,float*,int*,complex_float*,int*,float*,int*);
extern void F_FUNC(zgelsy,ZGELSY)(int*,int*,int*,complex_double*,int*,complex_double*,int*,int*,double*,int*,complex_double*,int*,double*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** sgelsy ***********************************/
static char doc_f2py_rout_gelsy_sgelsy[] = "\
Function signature:\n\
  b,numrank,info = sgelsy(a,b,jpvt,rcond,work,[m,n,nrhs,lda,ldb,lwork])\n\
Required arguments:\n"
"  a : input rank-2 array('f') with bounds (lda,*)\n"
"  b : input rank-2 array('f') with bounds (ldb,*)\n"
"  jpvt :  rank-1 array('i') with bounds (n)\n"
"  rcond : input float\n"
"  work : input rank-1 array('f') with bounds (*)\n"
"Optional arguments:\n"
"  m := lda input int\n"
"  n := shape(a,1) input int\n"
"  nrhs := shape(b,1) input int\n"
"  lda := shape(a,0) input int\n"
"  ldb := shape(b,0) input int\n"
"  lwork := shape(work,0) input int\n"
"Return objects:\n"
"  b : rank-2 array('f') with bounds (ldb,*)\n"
"  numrank : int\n"
"  info : int";
/* extern void F_FUNC(sgelsy,SGELSY)(int*,int*,int*,float*,int*,float*,int*,int*,float*,int*,float*,int*,int*); */
static PyObject *f2py_rout_gelsy_sgelsy(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,float*,int*,float*,int*,int*,float*,int*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int nrhs = 0;
  PyObject *nrhs_capi = Py_None;
  float *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int lda = 0;
  PyObject *lda_capi = Py_None;
  float *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int ldb = 0;
  PyObject *ldb_capi = Py_None;
  int *jpvt = NULL;
  npy_intp jpvt_Dims[1] = {-1};
  const int jpvt_Rank = 1;
  PyArrayObject *capi_jpvt_tmp = NULL;
  int capi_jpvt_intent = 0;
  PyObject *jpvt_capi = Py_None;
  float rcond = 0;
  PyObject *rcond_capi = Py_None;
  int numrank = 0;
  float *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  int lwork = 0;
  PyObject *lwork_capi = Py_None;
  int info = 0;
  static char *capi_kwlist[] = {"a","b","jpvt","rcond","work","m","n","nrhs","lda","ldb","lwork",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOOOO:gelsy.sgelsy",\
    capi_kwlist,&a_capi,&b_capi,&jpvt_capi,&rcond_capi,&work_capi,&m_capi,&n_capi,&nrhs_capi,&lda_capi,&ldb_capi,&lwork_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_FLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 1st argument `a' of gelsy.sgelsy to C/Fortran array" );
  } else {
    a = (float *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(PyArray_FLOAT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 2nd argument `b' of gelsy.sgelsy to C/Fortran array" );
  } else {
    b = (float *)(capi_b_tmp->data);

  /* Processing variable work */
  ;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(PyArray_FLOAT,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 5th argument `work' of gelsy.sgelsy to C/Fortran array" );
  } else {
    work = (float *)(capi_work_tmp->data);

  /* Processing variable info */
  /* Processing variable rcond */
    f2py_success = float_from_pyobj(&rcond,rcond_capi,"gelsy.sgelsy() 4th argument (rcond) can't be converted to float");
  if (f2py_success) {
  /* Processing variable numrank */
  /* Processing variable ldb */
  if (ldb_capi == Py_None) ldb = shape(b,0); else
    f2py_success = int_from_pyobj(&ldb,ldb_capi,"gelsy.sgelsy() 5th keyword (ldb) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==ldb,"shape(b,0)==ldb","5th keyword ldb","sgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=n,"ldb>=n","5th keyword ldb","sgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=m,"ldb>=m","5th keyword ldb","sgelsy:ldb=%d",ldb) {
  /* Processing variable lda */
  if (lda_capi == Py_None) lda = shape(a,0); else
    f2py_success = int_from_pyobj(&lda,lda_capi,"gelsy.sgelsy() 4th keyword (lda) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==lda,"shape(a,0)==lda","4th keyword lda","sgelsy:lda=%d",lda) {
  /* Processing variable m */
  if (m_capi == Py_None) m = lda; else
    f2py_success = int_from_pyobj(&m,m_capi,"gelsy.sgelsy() 1st keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(m<=lda,"m<=lda","1st keyword m","sgelsy:m=%d",m) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(a,1); else
    f2py_success = int_from_pyobj(&n,n_capi,"gelsy.sgelsy() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nrhs */
  if (nrhs_capi == Py_None) nrhs = shape(b,1); else
    f2py_success = int_from_pyobj(&nrhs,nrhs_capi,"gelsy.sgelsy() 3rd keyword (nrhs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lwork */
  if (lwork_capi == Py_None) lwork = shape(work,0); else
    f2py_success = int_from_pyobj(&lwork,lwork_capi,"gelsy.sgelsy() 6th keyword (lwork) can't be converted to int");
  if (f2py_success) {
  /* Processing variable jpvt */
  jpvt_Dims[0]=n;
  capi_jpvt_intent |= F2PY_INTENT_INPLACE;
  capi_jpvt_tmp = array_from_pyobj(PyArray_INT,jpvt_Dims,jpvt_Rank,capi_jpvt_intent,jpvt_capi);
  if (capi_jpvt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 3rd argument `jpvt' of gelsy.sgelsy to C/Fortran array" );
  } else {
    jpvt = (int *)(capi_jpvt_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&m,&n,&nrhs,a,&lda,b,&ldb,jpvt,&rcond,&numrank,work,&lwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Nii",capi_b_tmp,numrank,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_jpvt_tmp!=jpvt_capi) {
    Py_XDECREF(capi_jpvt_tmp); }
  }  /*if (capi_jpvt_tmp == NULL) ... else of jpvt*/
  /* End of cleaning variable jpvt */
  } /*if (f2py_success) of lwork*/
  /* End of cleaning variable lwork */
  } /*if (f2py_success) of nrhs*/
  /* End of cleaning variable nrhs */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(m<=lda)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*CHECKSCALAR(shape(a,0)==lda)*/
  } /*if (f2py_success) of lda*/
  /* End of cleaning variable lda */
  } /*CHECKSCALAR(ldb>=m)*/
  } /*CHECKSCALAR(ldb>=n)*/
  } /*CHECKSCALAR(shape(b,0)==ldb)*/
  } /*if (f2py_success) of ldb*/
  /* End of cleaning variable ldb */
  /* End of cleaning variable numrank */
  } /*if (f2py_success) of rcond*/
  /* End of cleaning variable rcond */
  /* End of cleaning variable info */
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of sgelsy *******************************/

/*********************************** dgelsy ***********************************/
static char doc_f2py_rout_gelsy_dgelsy[] = "\
Function signature:\n\
  b,numrank,info = dgelsy(a,b,jpvt,rcond,work,[m,n,nrhs,lda,ldb,lwork])\n\
Required arguments:\n"
"  a : input rank-2 array('d') with bounds (lda,*)\n"
"  b : input rank-2 array('d') with bounds (ldb,*)\n"
"  jpvt :  rank-1 array('i') with bounds (n)\n"
"  rcond : input float\n"
"  work : input rank-1 array('d') with bounds (*)\n"
"Optional arguments:\n"
"  m := lda input int\n"
"  n := shape(a,1) input int\n"
"  nrhs := shape(b,1) input int\n"
"  lda := shape(a,0) input int\n"
"  ldb := shape(b,0) input int\n"
"  lwork := shape(work,0) input int\n"
"Return objects:\n"
"  b : rank-2 array('d') with bounds (ldb,*)\n"
"  numrank : int\n"
"  info : int";
/* extern void F_FUNC(dgelsy,DGELSY)(int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,double*,int*,int*); */
static PyObject *f2py_rout_gelsy_dgelsy(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,double*,int*,double*,int*,int*,double*,int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int nrhs = 0;
  PyObject *nrhs_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int lda = 0;
  PyObject *lda_capi = Py_None;
  double *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int ldb = 0;
  PyObject *ldb_capi = Py_None;
  int *jpvt = NULL;
  npy_intp jpvt_Dims[1] = {-1};
  const int jpvt_Rank = 1;
  PyArrayObject *capi_jpvt_tmp = NULL;
  int capi_jpvt_intent = 0;
  PyObject *jpvt_capi = Py_None;
  double rcond = 0;
  PyObject *rcond_capi = Py_None;
  int numrank = 0;
  double *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  int lwork = 0;
  PyObject *lwork_capi = Py_None;
  int info = 0;
  static char *capi_kwlist[] = {"a","b","jpvt","rcond","work","m","n","nrhs","lda","ldb","lwork",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOOOO:gelsy.dgelsy",\
    capi_kwlist,&a_capi,&b_capi,&jpvt_capi,&rcond_capi,&work_capi,&m_capi,&n_capi,&nrhs_capi,&lda_capi,&ldb_capi,&lwork_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 1st argument `a' of gelsy.dgelsy to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(PyArray_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 2nd argument `b' of gelsy.dgelsy to C/Fortran array" );
  } else {
    b = (double *)(capi_b_tmp->data);

  /* Processing variable work */
  ;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(PyArray_DOUBLE,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 5th argument `work' of gelsy.dgelsy to C/Fortran array" );
  } else {
    work = (double *)(capi_work_tmp->data);

  /* Processing variable info */
  /* Processing variable rcond */
    f2py_success = double_from_pyobj(&rcond,rcond_capi,"gelsy.dgelsy() 4th argument (rcond) can't be converted to double");
  if (f2py_success) {
  /* Processing variable numrank */
  /* Processing variable ldb */
  if (ldb_capi == Py_None) ldb = shape(b,0); else
    f2py_success = int_from_pyobj(&ldb,ldb_capi,"gelsy.dgelsy() 5th keyword (ldb) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==ldb,"shape(b,0)==ldb","5th keyword ldb","dgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=n,"ldb>=n","5th keyword ldb","dgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=m,"ldb>=m","5th keyword ldb","dgelsy:ldb=%d",ldb) {
  /* Processing variable lda */
  if (lda_capi == Py_None) lda = shape(a,0); else
    f2py_success = int_from_pyobj(&lda,lda_capi,"gelsy.dgelsy() 4th keyword (lda) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==lda,"shape(a,0)==lda","4th keyword lda","dgelsy:lda=%d",lda) {
  /* Processing variable m */
  if (m_capi == Py_None) m = lda; else
    f2py_success = int_from_pyobj(&m,m_capi,"gelsy.dgelsy() 1st keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(m<=lda,"m<=lda","1st keyword m","dgelsy:m=%d",m) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(a,1); else
    f2py_success = int_from_pyobj(&n,n_capi,"gelsy.dgelsy() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nrhs */
  if (nrhs_capi == Py_None) nrhs = shape(b,1); else
    f2py_success = int_from_pyobj(&nrhs,nrhs_capi,"gelsy.dgelsy() 3rd keyword (nrhs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lwork */
  if (lwork_capi == Py_None) lwork = shape(work,0); else
    f2py_success = int_from_pyobj(&lwork,lwork_capi,"gelsy.dgelsy() 6th keyword (lwork) can't be converted to int");
  if (f2py_success) {
  /* Processing variable jpvt */
  jpvt_Dims[0]=n;
  capi_jpvt_intent |= F2PY_INTENT_INPLACE;
  capi_jpvt_tmp = array_from_pyobj(PyArray_INT,jpvt_Dims,jpvt_Rank,capi_jpvt_intent,jpvt_capi);
  if (capi_jpvt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 3rd argument `jpvt' of gelsy.dgelsy to C/Fortran array" );
  } else {
    jpvt = (int *)(capi_jpvt_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&m,&n,&nrhs,a,&lda,b,&ldb,jpvt,&rcond,&numrank,work,&lwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Nii",capi_b_tmp,numrank,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_jpvt_tmp!=jpvt_capi) {
    Py_XDECREF(capi_jpvt_tmp); }
  }  /*if (capi_jpvt_tmp == NULL) ... else of jpvt*/
  /* End of cleaning variable jpvt */
  } /*if (f2py_success) of lwork*/
  /* End of cleaning variable lwork */
  } /*if (f2py_success) of nrhs*/
  /* End of cleaning variable nrhs */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(m<=lda)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*CHECKSCALAR(shape(a,0)==lda)*/
  } /*if (f2py_success) of lda*/
  /* End of cleaning variable lda */
  } /*CHECKSCALAR(ldb>=m)*/
  } /*CHECKSCALAR(ldb>=n)*/
  } /*CHECKSCALAR(shape(b,0)==ldb)*/
  } /*if (f2py_success) of ldb*/
  /* End of cleaning variable ldb */
  /* End of cleaning variable numrank */
  } /*if (f2py_success) of rcond*/
  /* End of cleaning variable rcond */
  /* End of cleaning variable info */
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of dgelsy *******************************/

/*********************************** cgelsy ***********************************/
static char doc_f2py_rout_gelsy_cgelsy[] = "\
Function signature:\n\
  b,numrank,info = cgelsy(a,b,jpvt,rcond,work,rwork,[m,n,nrhs,lda,ldb,lwork])\n\
Required arguments:\n"
"  a : input rank-2 array('F') with bounds (lda,*)\n"
"  b : input rank-2 array('F') with bounds (ldb,*)\n"
"  jpvt :  rank-1 array('i') with bounds (n)\n"
"  rcond : input float\n"
"  work : input rank-1 array('F') with bounds (*)\n"
"  rwork : input rank-1 array('f') with bounds (*)\n"
"Optional arguments:\n"
"  m := lda input int\n"
"  n := shape(a,1) input int\n"
"  nrhs := shape(b,1) input int\n"
"  lda := shape(a,0) input int\n"
"  ldb := shape(b,0) input int\n"
"  lwork := shape(work,0) input int\n"
"Return objects:\n"
"  b : rank-2 array('F') with bounds (ldb,*)\n"
"  numrank : int\n"
"  info : int";
/* extern void F_FUNC(cgelsy,CGELSY)(int*,int*,int*,complex_float*,int*,complex_float*,int*,int*,float*,int*,complex_float*,int*,float*,int*); */
static PyObject *f2py_rout_gelsy_cgelsy(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,complex_float*,int*,complex_float*,int*,int*,float*,int*,complex_float*,int*,float*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int nrhs = 0;
  PyObject *nrhs_capi = Py_None;
  complex_float *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int lda = 0;
  PyObject *lda_capi = Py_None;
  complex_float *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int ldb = 0;
  PyObject *ldb_capi = Py_None;
  int *jpvt = NULL;
  npy_intp jpvt_Dims[1] = {-1};
  const int jpvt_Rank = 1;
  PyArrayObject *capi_jpvt_tmp = NULL;
  int capi_jpvt_intent = 0;
  PyObject *jpvt_capi = Py_None;
  float rcond = 0;
  PyObject *rcond_capi = Py_None;
  int numrank = 0;
  complex_float *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  int lwork = 0;
  PyObject *lwork_capi = Py_None;
  float *rwork = NULL;
  npy_intp rwork_Dims[1] = {-1};
  const int rwork_Rank = 1;
  PyArrayObject *capi_rwork_tmp = NULL;
  int capi_rwork_intent = 0;
  PyObject *rwork_capi = Py_None;
  int info = 0;
  static char *capi_kwlist[] = {"a","b","jpvt","rcond","work","rwork","m","n","nrhs","lda","ldb","lwork",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OOOOOO:gelsy.cgelsy",\
    capi_kwlist,&a_capi,&b_capi,&jpvt_capi,&rcond_capi,&work_capi,&rwork_capi,&m_capi,&n_capi,&nrhs_capi,&lda_capi,&ldb_capi,&lwork_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_CFLOAT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 1st argument `a' of gelsy.cgelsy to C/Fortran array" );
  } else {
    a = (complex_float *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(PyArray_CFLOAT,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 2nd argument `b' of gelsy.cgelsy to C/Fortran array" );
  } else {
    b = (complex_float *)(capi_b_tmp->data);

  /* Processing variable work */
  ;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(PyArray_CFLOAT,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 5th argument `work' of gelsy.cgelsy to C/Fortran array" );
  } else {
    work = (complex_float *)(capi_work_tmp->data);

  /* Processing variable info */
  /* Processing variable rcond */
    f2py_success = float_from_pyobj(&rcond,rcond_capi,"gelsy.cgelsy() 4th argument (rcond) can't be converted to float");
  if (f2py_success) {
  /* Processing variable numrank */
  /* Processing variable ldb */
  if (ldb_capi == Py_None) ldb = shape(b,0); else
    f2py_success = int_from_pyobj(&ldb,ldb_capi,"gelsy.cgelsy() 5th keyword (ldb) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==ldb,"shape(b,0)==ldb","5th keyword ldb","cgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=n,"ldb>=n","5th keyword ldb","cgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=m,"ldb>=m","5th keyword ldb","cgelsy:ldb=%d",ldb) {
  /* Processing variable lda */
  if (lda_capi == Py_None) lda = shape(a,0); else
    f2py_success = int_from_pyobj(&lda,lda_capi,"gelsy.cgelsy() 4th keyword (lda) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==lda,"shape(a,0)==lda","4th keyword lda","cgelsy:lda=%d",lda) {
  /* Processing variable m */
  if (m_capi == Py_None) m = lda; else
    f2py_success = int_from_pyobj(&m,m_capi,"gelsy.cgelsy() 1st keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(m<=lda,"m<=lda","1st keyword m","cgelsy:m=%d",m) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(a,1); else
    f2py_success = int_from_pyobj(&n,n_capi,"gelsy.cgelsy() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nrhs */
  if (nrhs_capi == Py_None) nrhs = shape(b,1); else
    f2py_success = int_from_pyobj(&nrhs,nrhs_capi,"gelsy.cgelsy() 3rd keyword (nrhs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lwork */
  if (lwork_capi == Py_None) lwork = shape(work,0); else
    f2py_success = int_from_pyobj(&lwork,lwork_capi,"gelsy.cgelsy() 6th keyword (lwork) can't be converted to int");
  if (f2py_success) {
  /* Processing variable jpvt */
  jpvt_Dims[0]=n;
  capi_jpvt_intent |= F2PY_INTENT_INPLACE;
  capi_jpvt_tmp = array_from_pyobj(PyArray_INT,jpvt_Dims,jpvt_Rank,capi_jpvt_intent,jpvt_capi);
  if (capi_jpvt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 3rd argument `jpvt' of gelsy.cgelsy to C/Fortran array" );
  } else {
    jpvt = (int *)(capi_jpvt_tmp->data);

  /* Processing variable rwork */
  ;
  capi_rwork_intent |= F2PY_INTENT_IN;
  capi_rwork_tmp = array_from_pyobj(PyArray_FLOAT,rwork_Dims,rwork_Rank,capi_rwork_intent,rwork_capi);
  if (capi_rwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 6th argument `rwork' of gelsy.cgelsy to C/Fortran array" );
  } else {
    rwork = (float *)(capi_rwork_tmp->data);

  CHECKARRAY(shape(rwork,0)>=2*n,"shape(rwork,0)>=2*n","6th argument rwork") {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&m,&n,&nrhs,a,&lda,b,&ldb,jpvt,&rcond,&numrank,work,&lwork,rwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("Nii",capi_b_tmp,numrank,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKARRAY(shape(rwork,0)>=2*n)*/
  if((PyObject *)capi_rwork_tmp!=rwork_capi) {
    Py_XDECREF(capi_rwork_tmp); }
  }  /*if (capi_rwork_tmp == NULL) ... else of rwork*/
  /* End of cleaning variable rwork */
  if((PyObject *)capi_jpvt_tmp!=jpvt_capi) {
    Py_XDECREF(capi_jpvt_tmp); }
  }  /*if (capi_jpvt_tmp == NULL) ... else of jpvt*/
  /* End of cleaning variable jpvt */
  } /*if (f2py_success) of lwork*/
  /* End of cleaning variable lwork */
  } /*if (f2py_success) of nrhs*/
  /* End of cleaning variable nrhs */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(m<=lda)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*CHECKSCALAR(shape(a,0)==lda)*/
  } /*if (f2py_success) of lda*/
  /* End of cleaning variable lda */
  } /*CHECKSCALAR(ldb>=m)*/
  } /*CHECKSCALAR(ldb>=n)*/
  } /*CHECKSCALAR(shape(b,0)==ldb)*/
  } /*if (f2py_success) of ldb*/
  /* End of cleaning variable ldb */
  /* End of cleaning variable numrank */
  } /*if (f2py_success) of rcond*/
  /* End of cleaning variable rcond */
  /* End of cleaning variable info */
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of cgelsy *******************************/

/*********************************** zgelsy ***********************************/
static char doc_f2py_rout_gelsy_zgelsy[] = "\
Function signature:\n\
  numrank,info = zgelsy(a,b,jpvt,rcond,work,rwork,[m,n,nrhs,lda,ldb,lwork])\n\
Required arguments:\n"
"  a : input rank-2 array('D') with bounds (lda,*)\n"
"  b :  rank-2 array('D') with bounds (ldb,*)\n"
"  jpvt :  rank-1 array('i') with bounds (n)\n"
"  rcond : input float\n"
"  work : input rank-1 array('D') with bounds (*)\n"
"  rwork : input rank-1 array('d') with bounds (*)\n"
"Optional arguments:\n"
"  m := lda input int\n"
"  n := shape(a,1) input int\n"
"  nrhs := shape(b,1) input int\n"
"  lda := shape(a,0) input int\n"
"  ldb := shape(b,0) input int\n"
"  lwork := shape(work,0) input int\n"
"Return objects:\n"
"  numrank : int\n"
"  info : int";
/* extern void F_FUNC(zgelsy,ZGELSY)(int*,int*,int*,complex_double*,int*,complex_double*,int*,int*,double*,int*,complex_double*,int*,double*,int*); */
static PyObject *f2py_rout_gelsy_zgelsy(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,complex_double*,int*,complex_double*,int*,int*,double*,int*,complex_double*,int*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int nrhs = 0;
  PyObject *nrhs_capi = Py_None;
  complex_double *a = NULL;
  npy_intp a_Dims[2] = {-1, -1};
  const int a_Rank = 2;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int lda = 0;
  PyObject *lda_capi = Py_None;
  complex_double *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  int ldb = 0;
  PyObject *ldb_capi = Py_None;
  int *jpvt = NULL;
  npy_intp jpvt_Dims[1] = {-1};
  const int jpvt_Rank = 1;
  PyArrayObject *capi_jpvt_tmp = NULL;
  int capi_jpvt_intent = 0;
  PyObject *jpvt_capi = Py_None;
  double rcond = 0;
  PyObject *rcond_capi = Py_None;
  int numrank = 0;
  complex_double *work = NULL;
  npy_intp work_Dims[1] = {-1};
  const int work_Rank = 1;
  PyArrayObject *capi_work_tmp = NULL;
  int capi_work_intent = 0;
  PyObject *work_capi = Py_None;
  int lwork = 0;
  PyObject *lwork_capi = Py_None;
  double *rwork = NULL;
  npy_intp rwork_Dims[1] = {-1};
  const int rwork_Rank = 1;
  PyArrayObject *capi_rwork_tmp = NULL;
  int capi_rwork_intent = 0;
  PyObject *rwork_capi = Py_None;
  int info = 0;
  static char *capi_kwlist[] = {"a","b","jpvt","rcond","work","rwork","m","n","nrhs","lda","ldb","lwork",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OOOOOO:gelsy.zgelsy",\
    capi_kwlist,&a_capi,&b_capi,&jpvt_capi,&rcond_capi,&work_capi,&rwork_capi,&m_capi,&n_capi,&nrhs_capi,&lda_capi,&ldb_capi,&lwork_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_CDOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 1st argument `a' of gelsy.zgelsy to C/Fortran array" );
  } else {
    a = (complex_double *)(capi_a_tmp->data);

  /* Processing variable b */
  ;
  capi_b_intent |= F2PY_INTENT_INPLACE;
  capi_b_tmp = array_from_pyobj(PyArray_CDOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 2nd argument `b' of gelsy.zgelsy to C/Fortran array" );
  } else {
    b = (complex_double *)(capi_b_tmp->data);

  /* Processing variable work */
  ;
  capi_work_intent |= F2PY_INTENT_IN;
  capi_work_tmp = array_from_pyobj(PyArray_CDOUBLE,work_Dims,work_Rank,capi_work_intent,work_capi);
  if (capi_work_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 5th argument `work' of gelsy.zgelsy to C/Fortran array" );
  } else {
    work = (complex_double *)(capi_work_tmp->data);

  /* Processing variable info */
  /* Processing variable rcond */
    f2py_success = double_from_pyobj(&rcond,rcond_capi,"gelsy.zgelsy() 4th argument (rcond) can't be converted to double");
  if (f2py_success) {
  /* Processing variable numrank */
  /* Processing variable ldb */
  if (ldb_capi == Py_None) ldb = shape(b,0); else
    f2py_success = int_from_pyobj(&ldb,ldb_capi,"gelsy.zgelsy() 5th keyword (ldb) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(b,0)==ldb,"shape(b,0)==ldb","5th keyword ldb","zgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=n,"ldb>=n","5th keyword ldb","zgelsy:ldb=%d",ldb) {
  CHECKSCALAR(ldb>=m,"ldb>=m","5th keyword ldb","zgelsy:ldb=%d",ldb) {
  /* Processing variable lda */
  if (lda_capi == Py_None) lda = shape(a,0); else
    f2py_success = int_from_pyobj(&lda,lda_capi,"gelsy.zgelsy() 4th keyword (lda) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(a,0)==lda,"shape(a,0)==lda","4th keyword lda","zgelsy:lda=%d",lda) {
  /* Processing variable m */
  if (m_capi == Py_None) m = lda; else
    f2py_success = int_from_pyobj(&m,m_capi,"gelsy.zgelsy() 1st keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(m<=lda,"m<=lda","1st keyword m","zgelsy:m=%d",m) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(a,1); else
    f2py_success = int_from_pyobj(&n,n_capi,"gelsy.zgelsy() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nrhs */
  if (nrhs_capi == Py_None) nrhs = shape(b,1); else
    f2py_success = int_from_pyobj(&nrhs,nrhs_capi,"gelsy.zgelsy() 3rd keyword (nrhs) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lwork */
  if (lwork_capi == Py_None) lwork = shape(work,0); else
    f2py_success = int_from_pyobj(&lwork,lwork_capi,"gelsy.zgelsy() 6th keyword (lwork) can't be converted to int");
  if (f2py_success) {
  /* Processing variable jpvt */
  jpvt_Dims[0]=n;
  capi_jpvt_intent |= F2PY_INTENT_INPLACE;
  capi_jpvt_tmp = array_from_pyobj(PyArray_INT,jpvt_Dims,jpvt_Rank,capi_jpvt_intent,jpvt_capi);
  if (capi_jpvt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 3rd argument `jpvt' of gelsy.zgelsy to C/Fortran array" );
  } else {
    jpvt = (int *)(capi_jpvt_tmp->data);

  /* Processing variable rwork */
  ;
  capi_rwork_intent |= F2PY_INTENT_IN;
  capi_rwork_tmp = array_from_pyobj(PyArray_DOUBLE,rwork_Dims,rwork_Rank,capi_rwork_intent,rwork_capi);
  if (capi_rwork_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gelsy_error,"failed in converting 6th argument `rwork' of gelsy.zgelsy to C/Fortran array" );
  } else {
    rwork = (double *)(capi_rwork_tmp->data);

  CHECKARRAY(shape(rwork,0)>=2*n,"shape(rwork,0)>=2*n","6th argument rwork") {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&m,&n,&nrhs,a,&lda,b,&ldb,jpvt,&rcond,&numrank,work,&lwork,rwork,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("ii",numrank,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKARRAY(shape(rwork,0)>=2*n)*/
  if((PyObject *)capi_rwork_tmp!=rwork_capi) {
    Py_XDECREF(capi_rwork_tmp); }
  }  /*if (capi_rwork_tmp == NULL) ... else of rwork*/
  /* End of cleaning variable rwork */
  if((PyObject *)capi_jpvt_tmp!=jpvt_capi) {
    Py_XDECREF(capi_jpvt_tmp); }
  }  /*if (capi_jpvt_tmp == NULL) ... else of jpvt*/
  /* End of cleaning variable jpvt */
  } /*if (f2py_success) of lwork*/
  /* End of cleaning variable lwork */
  } /*if (f2py_success) of nrhs*/
  /* End of cleaning variable nrhs */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(m<=lda)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*CHECKSCALAR(shape(a,0)==lda)*/
  } /*if (f2py_success) of lda*/
  /* End of cleaning variable lda */
  } /*CHECKSCALAR(ldb>=m)*/
  } /*CHECKSCALAR(ldb>=n)*/
  } /*CHECKSCALAR(shape(b,0)==ldb)*/
  } /*if (f2py_success) of ldb*/
  /* End of cleaning variable ldb */
  /* End of cleaning variable numrank */
  } /*if (f2py_success) of rcond*/
  /* End of cleaning variable rcond */
  /* End of cleaning variable info */
  if((PyObject *)capi_work_tmp!=work_capi) {
    Py_XDECREF(capi_work_tmp); }
  }  /*if (capi_work_tmp == NULL) ... else of work*/
  /* End of cleaning variable work */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of zgelsy *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"sgelsy",-1,{{-1}},0,(char *)F_FUNC(sgelsy,SGELSY),(f2py_init_func)f2py_rout_gelsy_sgelsy,doc_f2py_rout_gelsy_sgelsy},
  {"dgelsy",-1,{{-1}},0,(char *)F_FUNC(dgelsy,DGELSY),(f2py_init_func)f2py_rout_gelsy_dgelsy,doc_f2py_rout_gelsy_dgelsy},
  {"cgelsy",-1,{{-1}},0,(char *)F_FUNC(cgelsy,CGELSY),(f2py_init_func)f2py_rout_gelsy_cgelsy,doc_f2py_rout_gelsy_cgelsy},
  {"zgelsy",-1,{{-1}},0,(char *)F_FUNC(zgelsy,ZGELSY),(f2py_init_func)f2py_rout_gelsy_zgelsy,doc_f2py_rout_gelsy_zgelsy},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initgelsy(void) {
  int i;
  PyObject *m,*d, *s;
  m = gelsy_module = Py_InitModule("gelsy", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module gelsy (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'gelsy' is auto-generated with f2py (version:2_5237).\nFunctions:\n"
"  b,numrank,info = sgelsy(a,b,jpvt,rcond,work,m=lda,n=shape(a,1),nrhs=shape(b,1),lda=shape(a,0),ldb=shape(b,0),lwork=shape(work,0))\n"
"  b,numrank,info = dgelsy(a,b,jpvt,rcond,work,m=lda,n=shape(a,1),nrhs=shape(b,1),lda=shape(a,0),ldb=shape(b,0),lwork=shape(work,0))\n"
"  b,numrank,info = cgelsy(a,b,jpvt,rcond,work,rwork,m=lda,n=shape(a,1),nrhs=shape(b,1),lda=shape(a,0),ldb=shape(b,0),lwork=shape(work,0))\n"
"  numrank,info = zgelsy(a,b,jpvt,rcond,work,rwork,m=lda,n=shape(a,1),nrhs=shape(b,1),lda=shape(a,0),ldb=shape(b,0),lwork=shape(work,0))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  gelsy_error = PyErr_NewException ("gelsy.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"gelsy");
#endif

}
#ifdef __cplusplus
}
#endif
