/* File: icfsmodule.c
 * This file is auto-generated with f2py (version:2_5237).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct 27 11:51:19 2009
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *icfs_error;
static PyObject *icfs_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    PyErr_SetString(icfs_error,"("tcheck") failed for "name);\
    fprintf(stderr,show"\n",var);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = icfs_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = icfs_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(dicf,DICF)(int*,int*,double*,double*,int*,int*,int*,int*,int*,int*,int*,double*);
extern void F_FUNC(dicfs,DICFS)(int*,int*,double*,double*,int*,int*,double*,double*,int*,int*,int*,double*,int*,double*,double*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ dicf ************************************/
static char doc_f2py_rout_icfs_dicf[] = "\
Function signature:\n\
  info = dicf(nnz,a,diag,col_ptr,row_ind,indr,indf,list,w,[n,p])\n\
Required arguments:\n"
"  nnz : input int\n"
"  a : in/output rank-1 array('d') with bounds (*)\n"
"  diag : in/output rank-1 array('d') with bounds (n)\n"
"  col_ptr : in/output rank-1 array('i') with bounds (n + 1)\n"
"  row_ind : in/output rank-1 array('i') with bounds (*)\n"
"  indr : input rank-1 array('i') with bounds (n)\n"
"  indf : input rank-1 array('i') with bounds (n)\n"
"  list : input rank-1 array('i') with bounds (n)\n"
"  w : input rank-1 array('d') with bounds (n)\n"
"Optional arguments:\n"
"  n := len(diag) input int\n"
"  p := 5 input int\n"
"Return objects:\n"
"  info : int";
/* extern void F_FUNC(dicf,DICF)(int*,int*,double*,double*,int*,int*,int*,int*,int*,int*,int*,double*); */
static PyObject *f2py_rout_icfs_dicf(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,int*,int*,int*,int*,int*,int*,double*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  int nnz = 0;
  PyObject *nnz_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  double *diag = NULL;
  npy_intp diag_Dims[1] = {-1};
  const int diag_Rank = 1;
  PyArrayObject *capi_diag_tmp = NULL;
  int capi_diag_intent = 0;
  PyObject *diag_capi = Py_None;
  int *col_ptr = NULL;
  npy_intp col_ptr_Dims[1] = {-1};
  const int col_ptr_Rank = 1;
  PyArrayObject *capi_col_ptr_tmp = NULL;
  int capi_col_ptr_intent = 0;
  PyObject *col_ptr_capi = Py_None;
  int *row_ind = NULL;
  npy_intp row_ind_Dims[1] = {-1};
  const int row_ind_Rank = 1;
  PyArrayObject *capi_row_ind_tmp = NULL;
  int capi_row_ind_intent = 0;
  PyObject *row_ind_capi = Py_None;
  int p = 0;
  PyObject *p_capi = Py_None;
  int info = 0;
  int *indr = NULL;
  npy_intp indr_Dims[1] = {-1};
  const int indr_Rank = 1;
  PyArrayObject *capi_indr_tmp = NULL;
  int capi_indr_intent = 0;
  PyObject *indr_capi = Py_None;
  int *indf = NULL;
  npy_intp indf_Dims[1] = {-1};
  const int indf_Rank = 1;
  PyArrayObject *capi_indf_tmp = NULL;
  int capi_indf_intent = 0;
  PyObject *indf_capi = Py_None;
  int *list = NULL;
  npy_intp list_Dims[1] = {-1};
  const int list_Rank = 1;
  PyArrayObject *capi_list_tmp = NULL;
  int capi_list_intent = 0;
  PyObject *list_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  PyObject *w_capi = Py_None;
  static char *capi_kwlist[] = {"nnz","a","diag","col_ptr","row_ind","indr","indf","list","w","n","p",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOO|OO:icfs.dicf",\
    capi_kwlist,&nnz_capi,&a_capi,&diag_capi,&col_ptr_capi,&row_ind_capi,&indr_capi,&indf_capi,&list_capi,&w_capi,&n_capi,&p_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_INOUT;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 2nd argument `a' of icfs.dicf to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable row_ind */
  ;
  capi_row_ind_intent |= F2PY_INTENT_INOUT;
  capi_row_ind_tmp = array_from_pyobj(PyArray_INT,row_ind_Dims,row_ind_Rank,capi_row_ind_intent,row_ind_capi);
  if (capi_row_ind_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 5th argument `row_ind' of icfs.dicf to C/Fortran array" );
  } else {
    row_ind = (int *)(capi_row_ind_tmp->data);

  /* Processing variable diag */
  ;
  capi_diag_intent |= F2PY_INTENT_INOUT;
  capi_diag_tmp = array_from_pyobj(PyArray_DOUBLE,diag_Dims,diag_Rank,capi_diag_intent,diag_capi);
  if (capi_diag_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 3rd argument `diag' of icfs.dicf to C/Fortran array" );
  } else {
    diag = (double *)(capi_diag_tmp->data);

  /* Processing variable info */
  /* Processing variable nnz */
    f2py_success = int_from_pyobj(&nnz,nnz_capi,"icfs.dicf() 1st argument (nnz) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(diag); else
    f2py_success = int_from_pyobj(&n,n_capi,"icfs.dicf() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(diag)>=n,"len(diag)>=n","1st keyword n","dicf:n=%d",n) {
  /* Processing variable p */
  if (p_capi == Py_None) p = 5; else
    f2py_success = int_from_pyobj(&p,p_capi,"icfs.dicf() 2nd keyword (p) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(row_ind)>=nnz+n*p,"len(row_ind)>=nnz+n*p","2nd keyword p","dicf:p=%d",p) {
  CHECKSCALAR(len(a)>=nnz+n*p,"len(a)>=nnz+n*p","2nd keyword p","dicf:p=%d",p) {
  /* Processing variable w */
  w_Dims[0]=n;
  capi_w_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_w_tmp = array_from_pyobj(PyArray_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 9th argument `w' of icfs.dicf to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

  /* Processing variable indf */
  indf_Dims[0]=n;
  capi_indf_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_indf_tmp = array_from_pyobj(PyArray_INT,indf_Dims,indf_Rank,capi_indf_intent,indf_capi);
  if (capi_indf_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 7th argument `indf' of icfs.dicf to C/Fortran array" );
  } else {
    indf = (int *)(capi_indf_tmp->data);

  /* Processing variable indr */
  indr_Dims[0]=n;
  capi_indr_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_indr_tmp = array_from_pyobj(PyArray_INT,indr_Dims,indr_Rank,capi_indr_intent,indr_capi);
  if (capi_indr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 6th argument `indr' of icfs.dicf to C/Fortran array" );
  } else {
    indr = (int *)(capi_indr_tmp->data);

  /* Processing variable list */
  list_Dims[0]=n;
  capi_list_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_list_tmp = array_from_pyobj(PyArray_INT,list_Dims,list_Rank,capi_list_intent,list_capi);
  if (capi_list_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 8th argument `list' of icfs.dicf to C/Fortran array" );
  } else {
    list = (int *)(capi_list_tmp->data);

  /* Processing variable col_ptr */
  col_ptr_Dims[0]=n + 1;
  capi_col_ptr_intent |= F2PY_INTENT_INOUT;
  capi_col_ptr_tmp = array_from_pyobj(PyArray_INT,col_ptr_Dims,col_ptr_Rank,capi_col_ptr_intent,col_ptr_capi);
  if (capi_col_ptr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 4th argument `col_ptr' of icfs.dicf to C/Fortran array" );
  } else {
    col_ptr = (int *)(capi_col_ptr_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,&nnz,a,diag,col_ptr,row_ind,&p,&info,indr,indf,list,w);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_col_ptr_tmp!=col_ptr_capi) {
    Py_XDECREF(capi_col_ptr_tmp); }
  }  /*if (capi_col_ptr_tmp == NULL) ... else of col_ptr*/
  /* End of cleaning variable col_ptr */
  if((PyObject *)capi_list_tmp!=list_capi) {
    Py_XDECREF(capi_list_tmp); }
  }  /*if (capi_list_tmp == NULL) ... else of list*/
  /* End of cleaning variable list */
  if((PyObject *)capi_indr_tmp!=indr_capi) {
    Py_XDECREF(capi_indr_tmp); }
  }  /*if (capi_indr_tmp == NULL) ... else of indr*/
  /* End of cleaning variable indr */
  if((PyObject *)capi_indf_tmp!=indf_capi) {
    Py_XDECREF(capi_indf_tmp); }
  }  /*if (capi_indf_tmp == NULL) ... else of indf*/
  /* End of cleaning variable indf */
  if((PyObject *)capi_w_tmp!=w_capi) {
    Py_XDECREF(capi_w_tmp); }
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  } /*CHECKSCALAR(len(a)>=nnz+n*p)*/
  } /*CHECKSCALAR(len(row_ind)>=nnz+n*p)*/
  } /*if (f2py_success) of p*/
  /* End of cleaning variable p */
  } /*CHECKSCALAR(len(diag)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of nnz*/
  /* End of cleaning variable nnz */
  /* End of cleaning variable info */
  if((PyObject *)capi_diag_tmp!=diag_capi) {
    Py_XDECREF(capi_diag_tmp); }
  }  /*if (capi_diag_tmp == NULL) ... else of diag*/
  /* End of cleaning variable diag */
  if((PyObject *)capi_row_ind_tmp!=row_ind_capi) {
    Py_XDECREF(capi_row_ind_tmp); }
  }  /*if (capi_row_ind_tmp == NULL) ... else of row_ind*/
  /* End of cleaning variable row_ind */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of dicf ********************************/

/*********************************** dicfs ***********************************/
static char doc_f2py_rout_icfs_dicfs[] = "\
Function signature:\n\
  l,ldiag,lcol_ptr,lrow_ind,alpha,info = dicfs(a,adiag,acol_ptr,arow_ind,l,ldiag,lcol_ptr,lrow_ind,iwa,wa1,wa2,[n,nnz,p,alpha,offset])\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (nnz)\n"
"  adiag : input rank-1 array('d') with bounds (n)\n"
"  acol_ptr : input rank-1 array('i') with bounds (n + 1)\n"
"  arow_ind : input rank-1 array('i') with bounds (nnz)\n"
"  l : input rank-1 array('d') with bounds (nnz+n*p)\n"
"  ldiag : input rank-1 array('d') with bounds (n)\n"
"  lcol_ptr : input rank-1 array('i') with bounds (n + 1)\n"
"  lrow_ind : input rank-1 array('i') with bounds (nnz+n*p)\n"
"  iwa : input rank-1 array('i') with bounds (3 * n)\n"
"  wa1 : input rank-1 array('d') with bounds (n)\n"
"  wa2 : input rank-1 array('d') with bounds (n)\n"
"Optional arguments:\n"
"  n := len(adiag) input int\n"
"  nnz := len(a) input int\n"
"  p := 5 input int\n"
"  alpha := 0.001 input float\n"
"  offset := 1 input int\n"
"Return objects:\n"
"  l : rank-1 array('d') with bounds (nnz+n*p)\n"
"  ldiag : rank-1 array('d') with bounds (n)\n"
"  lcol_ptr : rank-1 array('i') with bounds (n + 1)\n"
"  lrow_ind : rank-1 array('i') with bounds (nnz+n*p)\n"
"  alpha : float\n"
"  info : int";
/* extern void F_FUNC(dicfs,DICFS)(int*,int*,double*,double*,int*,int*,double*,double*,int*,int*,int*,double*,int*,double*,double*,int*,int*); */
static PyObject *f2py_rout_icfs_dicfs(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,double*,double*,int*,int*,double*,double*,int*,int*,int*,double*,int*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  int nnz = 0;
  PyObject *nnz_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  double *adiag = NULL;
  npy_intp adiag_Dims[1] = {-1};
  const int adiag_Rank = 1;
  PyArrayObject *capi_adiag_tmp = NULL;
  int capi_adiag_intent = 0;
  PyObject *adiag_capi = Py_None;
  int *acol_ptr = NULL;
  npy_intp acol_ptr_Dims[1] = {-1};
  const int acol_ptr_Rank = 1;
  PyArrayObject *capi_acol_ptr_tmp = NULL;
  int capi_acol_ptr_intent = 0;
  PyObject *acol_ptr_capi = Py_None;
  int *arow_ind = NULL;
  npy_intp arow_ind_Dims[1] = {-1};
  const int arow_ind_Rank = 1;
  PyArrayObject *capi_arow_ind_tmp = NULL;
  int capi_arow_ind_intent = 0;
  PyObject *arow_ind_capi = Py_None;
  double *l = NULL;
  npy_intp l_Dims[1] = {-1};
  const int l_Rank = 1;
  PyArrayObject *capi_l_tmp = NULL;
  int capi_l_intent = 0;
  PyObject *l_capi = Py_None;
  double *ldiag = NULL;
  npy_intp ldiag_Dims[1] = {-1};
  const int ldiag_Rank = 1;
  PyArrayObject *capi_ldiag_tmp = NULL;
  int capi_ldiag_intent = 0;
  PyObject *ldiag_capi = Py_None;
  int *lcol_ptr = NULL;
  npy_intp lcol_ptr_Dims[1] = {-1};
  const int lcol_ptr_Rank = 1;
  PyArrayObject *capi_lcol_ptr_tmp = NULL;
  int capi_lcol_ptr_intent = 0;
  PyObject *lcol_ptr_capi = Py_None;
  int *lrow_ind = NULL;
  npy_intp lrow_ind_Dims[1] = {-1};
  const int lrow_ind_Rank = 1;
  PyArrayObject *capi_lrow_ind_tmp = NULL;
  int capi_lrow_ind_intent = 0;
  PyObject *lrow_ind_capi = Py_None;
  int p = 0;
  PyObject *p_capi = Py_None;
  double alpha = 0;
  PyObject *alpha_capi = Py_None;
  int *iwa = NULL;
  npy_intp iwa_Dims[1] = {-1};
  const int iwa_Rank = 1;
  PyArrayObject *capi_iwa_tmp = NULL;
  int capi_iwa_intent = 0;
  PyObject *iwa_capi = Py_None;
  double *wa1 = NULL;
  npy_intp wa1_Dims[1] = {-1};
  const int wa1_Rank = 1;
  PyArrayObject *capi_wa1_tmp = NULL;
  int capi_wa1_intent = 0;
  PyObject *wa1_capi = Py_None;
  double *wa2 = NULL;
  npy_intp wa2_Dims[1] = {-1};
  const int wa2_Rank = 1;
  PyArrayObject *capi_wa2_tmp = NULL;
  int capi_wa2_intent = 0;
  PyObject *wa2_capi = Py_None;
  int offset = 0;
  PyObject *offset_capi = Py_None;
  int info = 0;
  static char *capi_kwlist[] = {"a","adiag","acol_ptr","arow_ind","l","ldiag","lcol_ptr","lrow_ind","iwa","wa1","wa2","n","nnz","p","alpha","offset",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOO|OOOOO:icfs.dicfs",\
    capi_kwlist,&a_capi,&adiag_capi,&acol_ptr_capi,&arow_ind_capi,&l_capi,&ldiag_capi,&lcol_ptr_capi,&lrow_ind_capi,&iwa_capi,&wa1_capi,&wa2_capi,&n_capi,&nnz_capi,&p_capi,&alpha_capi,&offset_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 1st argument `a' of icfs.dicfs to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable offset */
  if (offset_capi == Py_None) offset = 1; else
    f2py_success = int_from_pyobj(&offset,offset_capi,"icfs.dicfs() 5th keyword (offset) can't be converted to int");
  if (f2py_success) {
  /* Processing variable alpha */
  if (alpha_capi == Py_None) alpha = 0.001; else
    f2py_success = double_from_pyobj(&alpha,alpha_capi,"icfs.dicfs() 4th keyword (alpha) can't be converted to double");
  if (f2py_success) {
  /* Processing variable adiag */
  ;
  capi_adiag_intent |= F2PY_INTENT_IN;
  capi_adiag_tmp = array_from_pyobj(PyArray_DOUBLE,adiag_Dims,adiag_Rank,capi_adiag_intent,adiag_capi);
  if (capi_adiag_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 2nd argument `adiag' of icfs.dicfs to C/Fortran array" );
  } else {
    adiag = (double *)(capi_adiag_tmp->data);

  /* Processing variable info */
  /* Processing variable p */
  if (p_capi == Py_None) p = 5; else
    f2py_success = int_from_pyobj(&p,p_capi,"icfs.dicfs() 3rd keyword (p) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nnz */
  if (nnz_capi == Py_None) nnz = len(a); else
    f2py_success = int_from_pyobj(&nnz,nnz_capi,"icfs.dicfs() 2nd keyword (nnz) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(a)>=nnz,"len(a)>=nnz","2nd keyword nnz","dicfs:nnz=%d",nnz) {
  /* Processing variable n */
  if (n_capi == Py_None) n = len(adiag); else
    f2py_success = int_from_pyobj(&n,n_capi,"icfs.dicfs() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(adiag)>=n,"len(adiag)>=n","1st keyword n","dicfs:n=%d",n) {
  /* Processing variable wa2 */
  wa2_Dims[0]=n;
  capi_wa2_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_wa2_tmp = array_from_pyobj(PyArray_DOUBLE,wa2_Dims,wa2_Rank,capi_wa2_intent,wa2_capi);
  if (capi_wa2_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 11st argument `wa2' of icfs.dicfs to C/Fortran array" );
  } else {
    wa2 = (double *)(capi_wa2_tmp->data);

  /* Processing variable wa1 */
  wa1_Dims[0]=n;
  capi_wa1_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_wa1_tmp = array_from_pyobj(PyArray_DOUBLE,wa1_Dims,wa1_Rank,capi_wa1_intent,wa1_capi);
  if (capi_wa1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 10th argument `wa1' of icfs.dicfs to C/Fortran array" );
  } else {
    wa1 = (double *)(capi_wa1_tmp->data);

  /* Processing variable lcol_ptr */
  lcol_ptr_Dims[0]=n + 1;
  capi_lcol_ptr_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_lcol_ptr_tmp = array_from_pyobj(PyArray_INT,lcol_ptr_Dims,lcol_ptr_Rank,capi_lcol_ptr_intent,lcol_ptr_capi);
  if (capi_lcol_ptr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 7th argument `lcol_ptr' of icfs.dicfs to C/Fortran array" );
  } else {
    lcol_ptr = (int *)(capi_lcol_ptr_tmp->data);

  /* Processing variable iwa */
  iwa_Dims[0]=3 * n;
  capi_iwa_intent |= F2PY_INTENT_CACHE|F2PY_INTENT_IN;
  capi_iwa_tmp = array_from_pyobj(PyArray_INT,iwa_Dims,iwa_Rank,capi_iwa_intent,iwa_capi);
  if (capi_iwa_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 9th argument `iwa' of icfs.dicfs to C/Fortran array" );
  } else {
    iwa = (int *)(capi_iwa_tmp->data);

  /* Processing variable arow_ind */
  arow_ind_Dims[0]=nnz;
  capi_arow_ind_intent |= F2PY_INTENT_IN;
  capi_arow_ind_tmp = array_from_pyobj(PyArray_INT,arow_ind_Dims,arow_ind_Rank,capi_arow_ind_intent,arow_ind_capi);
  if (capi_arow_ind_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 4th argument `arow_ind' of icfs.dicfs to C/Fortran array" );
  } else {
    arow_ind = (int *)(capi_arow_ind_tmp->data);

  /* Processing variable ldiag */
  ldiag_Dims[0]=n;
  capi_ldiag_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_ldiag_tmp = array_from_pyobj(PyArray_DOUBLE,ldiag_Dims,ldiag_Rank,capi_ldiag_intent,ldiag_capi);
  if (capi_ldiag_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 6th argument `ldiag' of icfs.dicfs to C/Fortran array" );
  } else {
    ldiag = (double *)(capi_ldiag_tmp->data);

  /* Processing variable acol_ptr */
  acol_ptr_Dims[0]=n + 1;
  capi_acol_ptr_intent |= F2PY_INTENT_IN;
  capi_acol_ptr_tmp = array_from_pyobj(PyArray_INT,acol_ptr_Dims,acol_ptr_Rank,capi_acol_ptr_intent,acol_ptr_capi);
  if (capi_acol_ptr_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 3rd argument `acol_ptr' of icfs.dicfs to C/Fortran array" );
  } else {
    acol_ptr = (int *)(capi_acol_ptr_tmp->data);

  /* Processing variable lrow_ind */
  lrow_ind_Dims[0]=nnz+n*p;
  capi_lrow_ind_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_lrow_ind_tmp = array_from_pyobj(PyArray_INT,lrow_ind_Dims,lrow_ind_Rank,capi_lrow_ind_intent,lrow_ind_capi);
  if (capi_lrow_ind_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 8th argument `lrow_ind' of icfs.dicfs to C/Fortran array" );
  } else {
    lrow_ind = (int *)(capi_lrow_ind_tmp->data);

  /* Processing variable l */
  l_Dims[0]=nnz+n*p;
  capi_l_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_l_tmp = array_from_pyobj(PyArray_DOUBLE,l_Dims,l_Rank,capi_l_intent,l_capi);
  if (capi_l_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(icfs_error,"failed in converting 5th argument `l' of icfs.dicfs to C/Fortran array" );
  } else {
    l = (double *)(capi_l_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,&nnz,a,adiag,acol_ptr,arow_ind,l,ldiag,lcol_ptr,lrow_ind,&p,&alpha,iwa,wa1,wa2,&offset,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNdi",capi_l_tmp,capi_ldiag_tmp,capi_lcol_ptr_tmp,capi_lrow_ind_tmp,alpha,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_l_tmp == NULL) ... else of l*/
  /* End of cleaning variable l */
  }  /*if (capi_lrow_ind_tmp == NULL) ... else of lrow_ind*/
  /* End of cleaning variable lrow_ind */
  if((PyObject *)capi_acol_ptr_tmp!=acol_ptr_capi) {
    Py_XDECREF(capi_acol_ptr_tmp); }
  }  /*if (capi_acol_ptr_tmp == NULL) ... else of acol_ptr*/
  /* End of cleaning variable acol_ptr */
  }  /*if (capi_ldiag_tmp == NULL) ... else of ldiag*/
  /* End of cleaning variable ldiag */
  if((PyObject *)capi_arow_ind_tmp!=arow_ind_capi) {
    Py_XDECREF(capi_arow_ind_tmp); }
  }  /*if (capi_arow_ind_tmp == NULL) ... else of arow_ind*/
  /* End of cleaning variable arow_ind */
  if((PyObject *)capi_iwa_tmp!=iwa_capi) {
    Py_XDECREF(capi_iwa_tmp); }
  }  /*if (capi_iwa_tmp == NULL) ... else of iwa*/
  /* End of cleaning variable iwa */
  }  /*if (capi_lcol_ptr_tmp == NULL) ... else of lcol_ptr*/
  /* End of cleaning variable lcol_ptr */
  if((PyObject *)capi_wa1_tmp!=wa1_capi) {
    Py_XDECREF(capi_wa1_tmp); }
  }  /*if (capi_wa1_tmp == NULL) ... else of wa1*/
  /* End of cleaning variable wa1 */
  if((PyObject *)capi_wa2_tmp!=wa2_capi) {
    Py_XDECREF(capi_wa2_tmp); }
  }  /*if (capi_wa2_tmp == NULL) ... else of wa2*/
  /* End of cleaning variable wa2 */
  } /*CHECKSCALAR(len(adiag)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(len(a)>=nnz)*/
  } /*if (f2py_success) of nnz*/
  /* End of cleaning variable nnz */
  } /*if (f2py_success) of p*/
  /* End of cleaning variable p */
  /* End of cleaning variable info */
  if((PyObject *)capi_adiag_tmp!=adiag_capi) {
    Py_XDECREF(capi_adiag_tmp); }
  }  /*if (capi_adiag_tmp == NULL) ... else of adiag*/
  /* End of cleaning variable adiag */
  } /*if (f2py_success) of alpha*/
  /* End of cleaning variable alpha */
  } /*if (f2py_success) of offset*/
  /* End of cleaning variable offset */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of dicfs ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"dicf",-1,{{-1}},0,(char *)F_FUNC(dicf,DICF),(f2py_init_func)f2py_rout_icfs_dicf,doc_f2py_rout_icfs_dicf},
  {"dicfs",-1,{{-1}},0,(char *)F_FUNC(dicfs,DICFS),(f2py_init_func)f2py_rout_icfs_dicfs,doc_f2py_rout_icfs_dicfs},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initicfs(void) {
  int i;
  PyObject *m,*d, *s;
  m = icfs_module = Py_InitModule("icfs", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module icfs (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'icfs' is auto-generated with f2py (version:2_5237).\nFunctions:\n"
"  info = dicf(nnz,a,diag,col_ptr,row_ind,indr,indf,list,w,n=len(diag),p=5)\n"
"  l,ldiag,lcol_ptr,lrow_ind,alpha,info = dicfs(a,adiag,acol_ptr,arow_ind,l,ldiag,lcol_ptr,lrow_ind,iwa,wa1,wa2,n=len(adiag),nnz=len(a),p=5,alpha=0.001,offset=1)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  icfs_error = PyErr_NewException ("icfs.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"icfs");
#endif

}
#ifdef __cplusplus
}
#endif
