/* File: ilutmodule.c
 * This file is auto-generated with f2py (version:2_5237).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct 27 11:51:19 2009
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *ilut_error;
static PyObject *ilut_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = ilut_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = ilut_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(ilu0,ILU0)(int*,double*,int*,int*,double*,int*,int*,double*,int*);
extern void F_FUNC(milu0,MILU0)(int*,double*,int*,int*,double*,int*,int*,double*,int*);
extern void F_FUNC(iluk,ILUK)(int*,double*,int*,int*,int*,double*,int*,int*,int*,int*,double*,int*,int*);
extern void F_FUNC(ilut,ILUT)(int*,double*,int*,int*,int*,double*,double*,int*,int*,int*,double*,int*,int*);
extern void F_FUNC(ilutp,ILUTP)(int*,double*,int*,int*,int*,double*,double*,int*,double*,int*,int*,int*,double*,int*,int*,int*);
extern void F_FUNC(ilud,ILUD)(int*,double*,int*,int*,double*,double*,double*,int*,int*,int*,double*,int*,int*);
extern void F_FUNC(lutsol,LUTSOL)(int*,double*,double*,double*,int*,int*);
extern void F_FUNC(lusol,LUSOL)(int*,double*,double*,double*,int*,int*);
extern void F_FUNC(iludp,ILUDP)(int*,double*,int*,int*,double*,double*,double*,int*,double*,int*,int*,int*,double*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ ilu0 ************************************/
static char doc_f2py_rout_ilut_ilu0[] = "\
Function signature:\n\
  alu,jlu,ju,ierr = ilu0(a,ja,ia)\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (len(a)+1)\n"
"  jlu : rank-1 array('i') with bounds (len(a)+1)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  ierr : int";
/* extern void F_FUNC(ilu0,ILU0)(int*,double*,int*,int*,double*,int*,int*,double*,int*); */
static PyObject *f2py_rout_ilut_ilu0(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,int*,int*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  double *iw = NULL;
  npy_intp iw_Dims[1] = {-1};
  const int iw_Rank = 1;
  PyArrayObject *capi_iw_tmp = NULL;
  int capi_iw_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|:ilut.ilu0",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.ilu0 to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.ilu0 to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.ilu0 to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jlu */
  jlu_Dims[0]=len(a)+1;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.ilu0 to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable iw */
  iw_Dims[0]=n;
  capi_iw_intent |= F2PY_INTENT_HIDE;
  capi_iw_tmp = array_from_pyobj(PyArray_DOUBLE,iw_Dims,iw_Rank,capi_iw_intent,Py_None);
  if (capi_iw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `iw' of ilut.ilu0 to C/Fortran array" );
  } else {
    iw = (double *)(capi_iw_tmp->data);

  /* Processing variable alu */
  alu_Dims[0]=len(a)+1;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.ilu0 to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.ilu0 to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,alu,jlu,ju,iw,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
    Py_XDECREF(capi_iw_tmp);
  }  /*if (capi_iw_tmp == NULL) ... else of iw*/
  /* End of cleaning variable iw */
  /* End of cleaning variable n */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of ilu0 ********************************/

/*********************************** milu0 ***********************************/
static char doc_f2py_rout_ilut_milu0[] = "\
Function signature:\n\
  alu,jlu,ju,ierr = milu0(a,ja,ia)\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (len(a)+1)\n"
"  jlu : rank-1 array('i') with bounds (len(a)+1)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  ierr : int";
/* extern void F_FUNC(milu0,MILU0)(int*,double*,int*,int*,double*,int*,int*,double*,int*); */
static PyObject *f2py_rout_ilut_milu0(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,int*,int*,double*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  double *iw = NULL;
  npy_intp iw_Dims[1] = {-1};
  const int iw_Rank = 1;
  PyArrayObject *capi_iw_tmp = NULL;
  int capi_iw_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|:ilut.milu0",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.milu0 to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.milu0 to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.milu0 to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jlu */
  jlu_Dims[0]=len(a)+1;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.milu0 to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable alu */
  alu_Dims[0]=len(a)+1;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.milu0 to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.milu0 to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable iw */
  iw_Dims[0]=n;
  capi_iw_intent |= F2PY_INTENT_HIDE;
  capi_iw_tmp = array_from_pyobj(PyArray_DOUBLE,iw_Dims,iw_Rank,capi_iw_intent,Py_None);
  if (capi_iw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `iw' of ilut.milu0 to C/Fortran array" );
  } else {
    iw = (double *)(capi_iw_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,alu,jlu,ju,iw,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    Py_XDECREF(capi_iw_tmp);
  }  /*if (capi_iw_tmp == NULL) ... else of iw*/
  /* End of cleaning variable iw */
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
  /* End of cleaning variable n */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of milu0 ********************************/

/************************************ iluk ************************************/
static char doc_f2py_rout_ilut_iluk[] = "\
Function signature:\n\
  alu,jlu,ju,ierr = iluk(a,ja,ia,lfil,iwk)\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  lfil : input int\n"
"  iwk : input int\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (iwk)\n"
"  jlu : rank-1 array('i') with bounds (iwk)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  ierr : int";
/* extern void F_FUNC(iluk,ILUK)(int*,double*,int*,int*,int*,double*,int*,int*,int*,int*,double*,int*,int*); */
static PyObject *f2py_rout_ilut_iluk(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,int*,double*,int*,int*,int*,int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  int lfil = 0;
  PyObject *lfil_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  int *levs = NULL;
  npy_intp levs_Dims[1] = {-1};
  const int levs_Rank = 1;
  PyArrayObject *capi_levs_tmp = NULL;
  int capi_levs_intent = 0;
  int iwk = 0;
  PyObject *iwk_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  int *jw = NULL;
  npy_intp jw_Dims[1] = {-1};
  const int jw_Rank = 1;
  PyArrayObject *capi_jw_tmp = NULL;
  int capi_jw_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia","lfil","iwk",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|:ilut.iluk",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi,&lfil_capi,&iwk_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.iluk to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable lfil */
    f2py_success = int_from_pyobj(&lfil,lfil_capi,"ilut.iluk() 4th argument (lfil) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iwk */
    f2py_success = int_from_pyobj(&iwk,iwk_capi,"ilut.iluk() 5th argument (iwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.iluk to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.iluk to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jlu */
  jlu_Dims[0]=iwk;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.iluk to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable levs */
  levs_Dims[0]=iwk;
  capi_levs_intent |= F2PY_INTENT_HIDE;
  capi_levs_tmp = array_from_pyobj(PyArray_INT,levs_Dims,levs_Rank,capi_levs_intent,Py_None);
  if (capi_levs_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `levs' of ilut.iluk to C/Fortran array" );
  } else {
    levs = (int *)(capi_levs_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable w */
  w_Dims[0]=n;
  capi_w_intent |= F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(PyArray_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `w' of ilut.iluk to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

  /* Processing variable alu */
  alu_Dims[0]=iwk;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.iluk to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.iluk to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable jw */
  jw_Dims[0]=3 * n;
  capi_jw_intent |= F2PY_INTENT_HIDE;
  capi_jw_tmp = array_from_pyobj(PyArray_INT,jw_Dims,jw_Rank,capi_jw_intent,Py_None);
  if (capi_jw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jw' of ilut.iluk to C/Fortran array" );
  } else {
    jw = (int *)(capi_jw_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,&lfil,alu,jlu,ju,levs,&iwk,w,jw,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    Py_XDECREF(capi_jw_tmp);
  }  /*if (capi_jw_tmp == NULL) ... else of jw*/
  /* End of cleaning variable jw */
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
    Py_XDECREF(capi_w_tmp);
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  /* End of cleaning variable n */
    Py_XDECREF(capi_levs_tmp);
  }  /*if (capi_levs_tmp == NULL) ... else of levs*/
  /* End of cleaning variable levs */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of iwk*/
  /* End of cleaning variable iwk */
  } /*if (f2py_success) of lfil*/
  /* End of cleaning variable lfil */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of iluk ********************************/

/************************************ ilut ************************************/
static char doc_f2py_rout_ilut_ilut[] = "\
Function signature:\n\
  alu,jlu,ju,ierr = ilut(a,ja,ia,lfil,droptol,iwk)\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  lfil : input int\n"
"  droptol : input float\n"
"  iwk : input int\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (iwk)\n"
"  jlu : rank-1 array('i') with bounds (iwk)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  ierr : int";
/* extern void F_FUNC(ilut,ILUT)(int*,double*,int*,int*,int*,double*,double*,int*,int*,int*,double*,int*,int*); */
static PyObject *f2py_rout_ilut_ilut(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,int*,double*,double*,int*,int*,int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  int lfil = 0;
  PyObject *lfil_capi = Py_None;
  double droptol = 0;
  PyObject *droptol_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  int iwk = 0;
  PyObject *iwk_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  int *jw = NULL;
  npy_intp jw_Dims[1] = {-1};
  const int jw_Rank = 1;
  PyArrayObject *capi_jw_tmp = NULL;
  int capi_jw_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia","lfil","droptol","iwk",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:ilut.ilut",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi,&lfil_capi,&droptol_capi,&iwk_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.ilut to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable lfil */
    f2py_success = int_from_pyobj(&lfil,lfil_capi,"ilut.ilut() 4th argument (lfil) can't be converted to int");
  if (f2py_success) {
  /* Processing variable droptol */
    f2py_success = double_from_pyobj(&droptol,droptol_capi,"ilut.ilut() 5th argument (droptol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable iwk */
    f2py_success = int_from_pyobj(&iwk,iwk_capi,"ilut.ilut() 6th argument (iwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.ilut to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.ilut to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jlu */
  jlu_Dims[0]=iwk;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.ilut to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable w */
  w_Dims[0]=n + 1;
  capi_w_intent |= F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(PyArray_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `w' of ilut.ilut to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

  /* Processing variable alu */
  alu_Dims[0]=iwk;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.ilut to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.ilut to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable jw */
  jw_Dims[0]=2 * n;
  capi_jw_intent |= F2PY_INTENT_HIDE;
  capi_jw_tmp = array_from_pyobj(PyArray_INT,jw_Dims,jw_Rank,capi_jw_intent,Py_None);
  if (capi_jw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jw' of ilut.ilut to C/Fortran array" );
  } else {
    jw = (int *)(capi_jw_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,&lfil,&droptol,alu,jlu,ju,&iwk,w,jw,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    Py_XDECREF(capi_jw_tmp);
  }  /*if (capi_jw_tmp == NULL) ... else of jw*/
  /* End of cleaning variable jw */
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
    Py_XDECREF(capi_w_tmp);
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  /* End of cleaning variable n */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of iwk*/
  /* End of cleaning variable iwk */
  } /*if (f2py_success) of droptol*/
  /* End of cleaning variable droptol */
  } /*if (f2py_success) of lfil*/
  /* End of cleaning variable lfil */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of ilut ********************************/

/*********************************** ilutp ***********************************/
static char doc_f2py_rout_ilut_ilutp[] = "\
Function signature:\n\
  alu,jlu,ju,iperm,ierr = ilutp(a,ja,ia,lfil,droptol,iwk,[permtol,mbloc])\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  lfil : input int\n"
"  droptol : input float\n"
"  iwk : input int\n"
"Optional arguments:\n"
"  permtol := 0.01 input float\n"
"  mbloc := n input int\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (iwk)\n"
"  jlu : rank-1 array('i') with bounds (iwk)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  iperm : rank-1 array('i') with bounds (2 * n)\n"
"  ierr : int";
/* extern void F_FUNC(ilutp,ILUTP)(int*,double*,int*,int*,int*,double*,double*,int*,double*,int*,int*,int*,double*,int*,int*,int*); */
static PyObject *f2py_rout_ilut_ilutp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,int*,double*,double*,int*,double*,int*,int*,int*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  int lfil = 0;
  PyObject *lfil_capi = Py_None;
  double droptol = 0;
  PyObject *droptol_capi = Py_None;
  double permtol = 0;
  PyObject *permtol_capi = Py_None;
  int mbloc = 0;
  PyObject *mbloc_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  int iwk = 0;
  PyObject *iwk_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  int *jw = NULL;
  npy_intp jw_Dims[1] = {-1};
  const int jw_Rank = 1;
  PyArrayObject *capi_jw_tmp = NULL;
  int capi_jw_intent = 0;
  int *iperm = NULL;
  npy_intp iperm_Dims[1] = {-1};
  const int iperm_Rank = 1;
  PyArrayObject *capi_iperm_tmp = NULL;
  int capi_iperm_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia","lfil","droptol","iwk","permtol","mbloc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|OO:ilut.ilutp",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi,&lfil_capi,&droptol_capi,&iwk_capi,&permtol_capi,&mbloc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable lfil */
    f2py_success = int_from_pyobj(&lfil,lfil_capi,"ilut.ilutp() 4th argument (lfil) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iwk */
    f2py_success = int_from_pyobj(&iwk,iwk_capi,"ilut.ilutp() 6th argument (iwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.ilutp to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.ilutp to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.ilutp to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable droptol */
    f2py_success = double_from_pyobj(&droptol,droptol_capi,"ilut.ilutp() 5th argument (droptol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable permtol */
  if (permtol_capi == Py_None) permtol = 0.01; else
    f2py_success = double_from_pyobj(&permtol,permtol_capi,"ilut.ilutp() 1st keyword (permtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable jlu */
  jlu_Dims[0]=iwk;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.ilutp to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable alu */
  alu_Dims[0]=iwk;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.ilutp to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable w */
  w_Dims[0]=n + 1;
  capi_w_intent |= F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(PyArray_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `w' of ilut.ilutp to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.ilutp to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable jw */
  jw_Dims[0]=2 * n;
  capi_jw_intent |= F2PY_INTENT_HIDE;
  capi_jw_tmp = array_from_pyobj(PyArray_INT,jw_Dims,jw_Rank,capi_jw_intent,Py_None);
  if (capi_jw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jw' of ilut.ilutp to C/Fortran array" );
  } else {
    jw = (int *)(capi_jw_tmp->data);

  /* Processing variable iperm */
  iperm_Dims[0]=2 * n;
  capi_iperm_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_iperm_tmp = array_from_pyobj(PyArray_INT,iperm_Dims,iperm_Rank,capi_iperm_intent,Py_None);
  if (capi_iperm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `iperm' of ilut.ilutp to C/Fortran array" );
  } else {
    iperm = (int *)(capi_iperm_tmp->data);

  /* Processing variable mbloc */
  if (mbloc_capi == Py_None) mbloc = n; else
    f2py_success = int_from_pyobj(&mbloc,mbloc_capi,"ilut.ilutp() 2nd keyword (mbloc) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,&lfil,&droptol,&permtol,&mbloc,alu,jlu,ju,&iwk,w,jw,iperm,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,capi_iperm_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of mbloc*/
  /* End of cleaning variable mbloc */
  }  /*if (capi_iperm_tmp == NULL) ... else of iperm*/
  /* End of cleaning variable iperm */
    Py_XDECREF(capi_jw_tmp);
  }  /*if (capi_jw_tmp == NULL) ... else of jw*/
  /* End of cleaning variable jw */
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
    Py_XDECREF(capi_w_tmp);
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  /* End of cleaning variable n */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  } /*if (f2py_success) of permtol*/
  /* End of cleaning variable permtol */
  } /*if (f2py_success) of droptol*/
  /* End of cleaning variable droptol */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of iwk*/
  /* End of cleaning variable iwk */
  } /*if (f2py_success) of lfil*/
  /* End of cleaning variable lfil */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of ilutp ********************************/

/************************************ ilud ************************************/
static char doc_f2py_rout_ilut_ilud[] = "\
Function signature:\n\
  alu,jlu,ju,ierr = ilud(a,ja,ia,alph,tol,iwk)\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  alph : input float\n"
"  tol : input float\n"
"  iwk : input int\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (iwk)\n"
"  jlu : rank-1 array('i') with bounds (iwk)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  ierr : int";
/* extern void F_FUNC(ilud,ILUD)(int*,double*,int*,int*,double*,double*,double*,int*,int*,int*,double*,int*,int*); */
static PyObject *f2py_rout_ilut_ilud(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,double*,double*,int*,int*,int*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  double alph = 0;
  PyObject *alph_capi = Py_None;
  double tol = 0;
  PyObject *tol_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  int iwk = 0;
  PyObject *iwk_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  int *jw = NULL;
  npy_intp jw_Dims[1] = {-1};
  const int jw_Rank = 1;
  PyArrayObject *capi_jw_tmp = NULL;
  int capi_jw_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia","alph","tol","iwk",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOO|:ilut.ilud",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi,&alph_capi,&tol_capi,&iwk_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.ilud to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable alph */
    f2py_success = double_from_pyobj(&alph,alph_capi,"ilut.ilud() 4th argument (alph) can't be converted to double");
  if (f2py_success) {
  /* Processing variable tol */
    f2py_success = double_from_pyobj(&tol,tol_capi,"ilut.ilud() 5th argument (tol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable iwk */
    f2py_success = int_from_pyobj(&iwk,iwk_capi,"ilut.ilud() 6th argument (iwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.ilud to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.ilud to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable jlu */
  jlu_Dims[0]=iwk;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.ilud to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable w */
  w_Dims[0]=2 * n;
  capi_w_intent |= F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(PyArray_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `w' of ilut.ilud to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

  /* Processing variable alu */
  alu_Dims[0]=iwk;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.ilud to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.ilud to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable jw */
  jw_Dims[0]=2 * n;
  capi_jw_intent |= F2PY_INTENT_HIDE;
  capi_jw_tmp = array_from_pyobj(PyArray_INT,jw_Dims,jw_Rank,capi_jw_intent,Py_None);
  if (capi_jw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jw' of ilut.ilud to C/Fortran array" );
  } else {
    jw = (int *)(capi_jw_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,&alph,&tol,alu,jlu,ju,&iwk,w,jw,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    Py_XDECREF(capi_jw_tmp);
  }  /*if (capi_jw_tmp == NULL) ... else of jw*/
  /* End of cleaning variable jw */
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
    Py_XDECREF(capi_w_tmp);
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  /* End of cleaning variable n */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of iwk*/
  /* End of cleaning variable iwk */
  } /*if (f2py_success) of tol*/
  /* End of cleaning variable tol */
  } /*if (f2py_success) of alph*/
  /* End of cleaning variable alph */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of ilud ********************************/

/*********************************** lutsol ***********************************/
static char doc_f2py_rout_ilut_lutsol[] = "\
Function signature:\n\
  x = lutsol(y,x,alu,jlu,ju)\n\
Required arguments:\n"
"  y : input rank-1 array('d') with bounds (*)\n"
"  x : input rank-1 array('d') with bounds (len(y))\n"
"  alu : input rank-1 array('d') with bounds (*)\n"
"  jlu : input rank-1 array('i') with bounds (*)\n"
"  ju : input rank-1 array('i') with bounds (*)\n"
"Return objects:\n"
"  x : rank-1 array('d') with bounds (len(y))";
/* extern void F_FUNC(lutsol,LUTSOL)(int*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_ilut_lutsol(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  PyObject *alu_capi = Py_None;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  PyObject *jlu_capi = Py_None;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  PyObject *ju_capi = Py_None;
  static char *capi_kwlist[] = {"y","x","alu","jlu","ju",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|:ilut.lutsol",\
    capi_kwlist,&y_capi,&x_capi,&alu_capi,&jlu_capi,&ju_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable jlu */
  ;
  capi_jlu_intent |= F2PY_INTENT_IN;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,jlu_capi);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 4th argument `jlu' of ilut.lutsol to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(PyArray_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `y' of ilut.lutsol to C/Fortran array" );
  } else {
    y = (double *)(capi_y_tmp->data);

  /* Processing variable ju */
  ;
  capi_ju_intent |= F2PY_INTENT_IN;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,ju_capi);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 5th argument `ju' of ilut.lutsol to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable alu */
  ;
  capi_alu_intent |= F2PY_INTENT_IN;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,alu_capi);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `alu' of ilut.lutsol to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable x */
  x_Dims[0]=len(y);
  capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(PyArray_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `x' of ilut.lutsol to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable n */
  n = len(y);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,y,x,alu,jlu,ju);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_x_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable n */
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_alu_tmp!=alu_capi) {
    Py_XDECREF(capi_alu_tmp); }
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
  if((PyObject *)capi_ju_tmp!=ju_capi) {
    Py_XDECREF(capi_ju_tmp); }
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_jlu_tmp!=jlu_capi) {
    Py_XDECREF(capi_jlu_tmp); }
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of lutsol *******************************/

/*********************************** lusol ***********************************/
static char doc_f2py_rout_ilut_lusol[] = "\
Function signature:\n\
  x = lusol(y,x,alu,jlu,ju)\n\
Required arguments:\n"
"  y : input rank-1 array('d') with bounds (*)\n"
"  x : input rank-1 array('d') with bounds (len(y))\n"
"  alu : input rank-1 array('d') with bounds (*)\n"
"  jlu : input rank-1 array('i') with bounds (*)\n"
"  ju : input rank-1 array('i') with bounds (*)\n"
"Return objects:\n"
"  x : rank-1 array('d') with bounds (len(y))";
/* extern void F_FUNC(lusol,LUSOL)(int*,double*,double*,double*,int*,int*); */
static PyObject *f2py_rout_ilut_lusol(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,double*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *y = NULL;
  npy_intp y_Dims[1] = {-1};
  const int y_Rank = 1;
  PyArrayObject *capi_y_tmp = NULL;
  int capi_y_intent = 0;
  PyObject *y_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  PyObject *alu_capi = Py_None;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  PyObject *jlu_capi = Py_None;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  PyObject *ju_capi = Py_None;
  static char *capi_kwlist[] = {"y","x","alu","jlu","ju",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|:ilut.lusol",\
    capi_kwlist,&y_capi,&x_capi,&alu_capi,&jlu_capi,&ju_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable jlu */
  ;
  capi_jlu_intent |= F2PY_INTENT_IN;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,jlu_capi);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 4th argument `jlu' of ilut.lusol to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable y */
  ;
  capi_y_intent |= F2PY_INTENT_IN;
  capi_y_tmp = array_from_pyobj(PyArray_DOUBLE,y_Dims,y_Rank,capi_y_intent,y_capi);
  if (capi_y_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `y' of ilut.lusol to C/Fortran array" );
  } else {
    y = (double *)(capi_y_tmp->data);

  /* Processing variable ju */
  ;
  capi_ju_intent |= F2PY_INTENT_IN;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,ju_capi);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 5th argument `ju' of ilut.lusol to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable alu */
  ;
  capi_alu_intent |= F2PY_INTENT_IN;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,alu_capi);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `alu' of ilut.lusol to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable x */
  x_Dims[0]=len(y);
  capi_x_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_x_tmp = array_from_pyobj(PyArray_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `x' of ilut.lusol to C/Fortran array" );
  } else {
    x = (double *)(capi_x_tmp->data);

  /* Processing variable n */
  n = len(y);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,y,x,alu,jlu,ju);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_x_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable n */
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_alu_tmp!=alu_capi) {
    Py_XDECREF(capi_alu_tmp); }
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
  if((PyObject *)capi_ju_tmp!=ju_capi) {
    Py_XDECREF(capi_ju_tmp); }
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
  if((PyObject *)capi_y_tmp!=y_capi) {
    Py_XDECREF(capi_y_tmp); }
  }  /*if (capi_y_tmp == NULL) ... else of y*/
  /* End of cleaning variable y */
  if((PyObject *)capi_jlu_tmp!=jlu_capi) {
    Py_XDECREF(capi_jlu_tmp); }
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of lusol ********************************/

/*********************************** iludp ***********************************/
static char doc_f2py_rout_ilut_iludp[] = "\
Function signature:\n\
  alu,jlu,ju,iperm,ierr = iludp(a,ja,ia,droptol,iwk,[alph,permtol,mbloc])\n\
Required arguments:\n"
"  a : input rank-1 array('d') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  droptol : input float\n"
"  iwk : input int\n"
"Optional arguments:\n"
"  alph := 0.5 input float\n"
"  permtol := 0.01 input float\n"
"  mbloc := n input int\n"
"Return objects:\n"
"  alu : rank-1 array('d') with bounds (iwk)\n"
"  jlu : rank-1 array('i') with bounds (iwk)\n"
"  ju : rank-1 array('i') with bounds (n)\n"
"  iperm : rank-1 array('i') with bounds (2 * n)\n"
"  ierr : int";
/* extern void F_FUNC(iludp,ILUDP)(int*,double*,int*,int*,double*,double*,double*,int*,double*,int*,int*,int*,double*,int*,int*,int*); */
static PyObject *f2py_rout_ilut_iludp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,int*,int*,double*,double*,double*,int*,double*,int*,int*,int*,double*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  double alph = 0;
  PyObject *alph_capi = Py_None;
  double droptol = 0;
  PyObject *droptol_capi = Py_None;
  double permtol = 0;
  PyObject *permtol_capi = Py_None;
  int mbloc = 0;
  PyObject *mbloc_capi = Py_None;
  double *alu = NULL;
  npy_intp alu_Dims[1] = {-1};
  const int alu_Rank = 1;
  PyArrayObject *capi_alu_tmp = NULL;
  int capi_alu_intent = 0;
  int *jlu = NULL;
  npy_intp jlu_Dims[1] = {-1};
  const int jlu_Rank = 1;
  PyArrayObject *capi_jlu_tmp = NULL;
  int capi_jlu_intent = 0;
  int *ju = NULL;
  npy_intp ju_Dims[1] = {-1};
  const int ju_Rank = 1;
  PyArrayObject *capi_ju_tmp = NULL;
  int capi_ju_intent = 0;
  int iwk = 0;
  PyObject *iwk_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  int *jw = NULL;
  npy_intp jw_Dims[1] = {-1};
  const int jw_Rank = 1;
  PyArrayObject *capi_jw_tmp = NULL;
  int capi_jw_intent = 0;
  int *iperm = NULL;
  npy_intp iperm_Dims[1] = {-1};
  const int iperm_Rank = 1;
  PyArrayObject *capi_iperm_tmp = NULL;
  int capi_iperm_intent = 0;
  int ierr = 0;
  static char *capi_kwlist[] = {"a","ja","ia","droptol","iwk","alph","permtol","mbloc",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOO:ilut.iludp",\
    capi_kwlist,&a_capi,&ja_capi,&ia_capi,&droptol_capi,&iwk_capi,&alph_capi,&permtol_capi,&mbloc_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iwk */
    f2py_success = int_from_pyobj(&iwk,iwk_capi,"ilut.iludp() 5th argument (iwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ierr */
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 3rd argument `ia' of ilut.iludp to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 2nd argument `ja' of ilut.iludp to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting 1st argument `a' of ilut.iludp to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable droptol */
    f2py_success = double_from_pyobj(&droptol,droptol_capi,"ilut.iludp() 4th argument (droptol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable permtol */
  if (permtol_capi == Py_None) permtol = 0.01; else
    f2py_success = double_from_pyobj(&permtol,permtol_capi,"ilut.iludp() 2nd keyword (permtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable alph */
  if (alph_capi == Py_None) alph = 0.5; else
    f2py_success = double_from_pyobj(&alph,alph_capi,"ilut.iludp() 1st keyword (alph) can't be converted to double");
  if (f2py_success) {
  /* Processing variable jlu */
  jlu_Dims[0]=iwk;
  capi_jlu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_jlu_tmp = array_from_pyobj(PyArray_INT,jlu_Dims,jlu_Rank,capi_jlu_intent,Py_None);
  if (capi_jlu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jlu' of ilut.iludp to C/Fortran array" );
  } else {
    jlu = (int *)(capi_jlu_tmp->data);

  /* Processing variable alu */
  alu_Dims[0]=iwk;
  capi_alu_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_alu_tmp = array_from_pyobj(PyArray_DOUBLE,alu_Dims,alu_Rank,capi_alu_intent,Py_None);
  if (capi_alu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `alu' of ilut.iludp to C/Fortran array" );
  } else {
    alu = (double *)(capi_alu_tmp->data);

  /* Processing variable n */
  n = (len(ia)-1);
  /* Processing variable w */
  w_Dims[0]=2 * n;
  capi_w_intent |= F2PY_INTENT_HIDE;
  capi_w_tmp = array_from_pyobj(PyArray_DOUBLE,w_Dims,w_Rank,capi_w_intent,Py_None);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `w' of ilut.iludp to C/Fortran array" );
  } else {
    w = (double *)(capi_w_tmp->data);

  /* Processing variable ju */
  ju_Dims[0]=n;
  capi_ju_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ju_tmp = array_from_pyobj(PyArray_INT,ju_Dims,ju_Rank,capi_ju_intent,Py_None);
  if (capi_ju_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `ju' of ilut.iludp to C/Fortran array" );
  } else {
    ju = (int *)(capi_ju_tmp->data);

  /* Processing variable jw */
  jw_Dims[0]=2 * n;
  capi_jw_intent |= F2PY_INTENT_HIDE;
  capi_jw_tmp = array_from_pyobj(PyArray_INT,jw_Dims,jw_Rank,capi_jw_intent,Py_None);
  if (capi_jw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `jw' of ilut.iludp to C/Fortran array" );
  } else {
    jw = (int *)(capi_jw_tmp->data);

  /* Processing variable iperm */
  iperm_Dims[0]=2 * n;
  capi_iperm_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_iperm_tmp = array_from_pyobj(PyArray_INT,iperm_Dims,iperm_Rank,capi_iperm_intent,Py_None);
  if (capi_iperm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ilut_error,"failed in converting hidden `iperm' of ilut.iludp to C/Fortran array" );
  } else {
    iperm = (int *)(capi_iperm_tmp->data);

  /* Processing variable mbloc */
  if (mbloc_capi == Py_None) mbloc = n; else
    f2py_success = int_from_pyobj(&mbloc,mbloc_capi,"ilut.iludp() 3rd keyword (mbloc) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a,ja,ia,&alph,&droptol,&permtol,&mbloc,alu,jlu,ju,&iwk,w,jw,iperm,&ierr);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNi",capi_alu_tmp,capi_jlu_tmp,capi_ju_tmp,capi_iperm_tmp,ierr);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of mbloc*/
  /* End of cleaning variable mbloc */
  }  /*if (capi_iperm_tmp == NULL) ... else of iperm*/
  /* End of cleaning variable iperm */
    Py_XDECREF(capi_jw_tmp);
  }  /*if (capi_jw_tmp == NULL) ... else of jw*/
  /* End of cleaning variable jw */
  }  /*if (capi_ju_tmp == NULL) ... else of ju*/
  /* End of cleaning variable ju */
    Py_XDECREF(capi_w_tmp);
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  /* End of cleaning variable n */
  }  /*if (capi_alu_tmp == NULL) ... else of alu*/
  /* End of cleaning variable alu */
  }  /*if (capi_jlu_tmp == NULL) ... else of jlu*/
  /* End of cleaning variable jlu */
  } /*if (f2py_success) of alph*/
  /* End of cleaning variable alph */
  } /*if (f2py_success) of permtol*/
  /* End of cleaning variable permtol */
  } /*if (f2py_success) of droptol*/
  /* End of cleaning variable droptol */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  /* End of cleaning variable ierr */
  } /*if (f2py_success) of iwk*/
  /* End of cleaning variable iwk */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of iludp ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"ilu0",-1,{{-1}},0,(char *)F_FUNC(ilu0,ILU0),(f2py_init_func)f2py_rout_ilut_ilu0,doc_f2py_rout_ilut_ilu0},
  {"milu0",-1,{{-1}},0,(char *)F_FUNC(milu0,MILU0),(f2py_init_func)f2py_rout_ilut_milu0,doc_f2py_rout_ilut_milu0},
  {"iluk",-1,{{-1}},0,(char *)F_FUNC(iluk,ILUK),(f2py_init_func)f2py_rout_ilut_iluk,doc_f2py_rout_ilut_iluk},
  {"ilut",-1,{{-1}},0,(char *)F_FUNC(ilut,ILUT),(f2py_init_func)f2py_rout_ilut_ilut,doc_f2py_rout_ilut_ilut},
  {"ilutp",-1,{{-1}},0,(char *)F_FUNC(ilutp,ILUTP),(f2py_init_func)f2py_rout_ilut_ilutp,doc_f2py_rout_ilut_ilutp},
  {"ilud",-1,{{-1}},0,(char *)F_FUNC(ilud,ILUD),(f2py_init_func)f2py_rout_ilut_ilud,doc_f2py_rout_ilut_ilud},
  {"lutsol",-1,{{-1}},0,(char *)F_FUNC(lutsol,LUTSOL),(f2py_init_func)f2py_rout_ilut_lutsol,doc_f2py_rout_ilut_lutsol},
  {"lusol",-1,{{-1}},0,(char *)F_FUNC(lusol,LUSOL),(f2py_init_func)f2py_rout_ilut_lusol,doc_f2py_rout_ilut_lusol},
  {"iludp",-1,{{-1}},0,(char *)F_FUNC(iludp,ILUDP),(f2py_init_func)f2py_rout_ilut_iludp,doc_f2py_rout_ilut_iludp},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initilut(void) {
  int i;
  PyObject *m,*d, *s;
  m = ilut_module = Py_InitModule("ilut", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module ilut (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'ilut' is auto-generated with f2py (version:2_5237).\nFunctions:\n"
"  alu,jlu,ju,ierr = ilu0(a,ja,ia)\n"
"  alu,jlu,ju,ierr = milu0(a,ja,ia)\n"
"  alu,jlu,ju,ierr = iluk(a,ja,ia,lfil,iwk)\n"
"  alu,jlu,ju,ierr = ilut(a,ja,ia,lfil,droptol,iwk)\n"
"  alu,jlu,ju,iperm,ierr = ilutp(a,ja,ia,lfil,droptol,iwk,permtol=0.01,mbloc=n)\n"
"  alu,jlu,ju,ierr = ilud(a,ja,ia,alph,tol,iwk)\n"
"  x = lutsol(y,x,alu,jlu,ju)\n"
"  x = lusol(y,x,alu,jlu,ju)\n"
"  alu,jlu,ju,iperm,ierr = iludp(a,ja,ia,droptol,iwk,alph=0.5,permtol=0.01,mbloc=n)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  ilut_error = PyErr_NewException ("ilut.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));









/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"ilut");
#endif

}
#ifdef __cplusplus
}
#endif
