/* File: rcmmodule.c
 * This file is auto-generated with f2py (version:2_5237).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct 27 11:51:19 2009
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *rcm_error;
static PyObject *rcm_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#define CHECKSCALAR(check,tcheck,name,show,var)\
  if (!(check)) {\
    PyErr_SetString(rcm_error,"("tcheck") failed for "name);\
    fprintf(stderr,show"\n",var);\
    /*goto capi_fail;*/\
  } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = rcm_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(genrcm,GENRCM)(int*,int*,int*,int*);
extern void F_FUNC_US(root_find,ROOT_FIND)(int*,int*,int*,int*,int*,int*,int*,int*);
extern void F_FUNC_US(level_set,LEVEL_SET)(int*,int*,int*,int*,int*,int*,int*,int*);
extern void F_FUNC(rcm,RCM)(int*,int*,int*,int*,int*,int*,int*);
extern void F_FUNC(degree,DEGREE)(int*,int*,int*,int*,int*,int*,int*,int*);
extern void F_FUNC_US(ivec_reverse,IVEC_REVERSE)(int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** genrcm ***********************************/
static char doc_f2py_rout_rcm_genrcm[] = "\
Function signature:\n\
  perm = genrcm(adj_row,adj,[n])\n\
Required arguments:\n"
"  adj_row : input rank-1 array('i') with bounds (n + 1)\n"
"  adj : input rank-1 array('i') with bounds (*)\n"
"Optional arguments:\n"
"  n := (len(adj_row)-1) input int\n"
"Return objects:\n"
"  perm : rank-1 array('i') with bounds (n)";
/* extern void F_FUNC(genrcm,GENRCM)(int*,int*,int*,int*); */
static PyObject *f2py_rout_rcm_genrcm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  int *adj_row = NULL;
  npy_intp adj_row_Dims[1] = {-1};
  const int adj_row_Rank = 1;
  PyArrayObject *capi_adj_row_tmp = NULL;
  int capi_adj_row_intent = 0;
  PyObject *adj_row_capi = Py_None;
  int *adj = NULL;
  npy_intp adj_Dims[1] = {-1};
  const int adj_Rank = 1;
  PyArrayObject *capi_adj_tmp = NULL;
  int capi_adj_intent = 0;
  PyObject *adj_capi = Py_None;
  int *perm = NULL;
  npy_intp perm_Dims[1] = {-1};
  const int perm_Rank = 1;
  PyArrayObject *capi_perm_tmp = NULL;
  int capi_perm_intent = 0;
  static char *capi_kwlist[] = {"adj_row","adj","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|O:rcm.genrcm",\
    capi_kwlist,&adj_row_capi,&adj_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable adj_row */
  ;
  capi_adj_row_intent |= F2PY_INTENT_IN;
  capi_adj_row_tmp = array_from_pyobj(PyArray_INT,adj_row_Dims,adj_row_Rank,capi_adj_row_intent,adj_row_capi);
  if (capi_adj_row_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 1st argument `adj_row' of rcm.genrcm to C/Fortran array" );
  } else {
    adj_row = (int *)(capi_adj_row_tmp->data);

  /* Processing variable adj */
  ;
  capi_adj_intent |= F2PY_INTENT_IN;
  capi_adj_tmp = array_from_pyobj(PyArray_INT,adj_Dims,adj_Rank,capi_adj_intent,adj_capi);
  if (capi_adj_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 2nd argument `adj' of rcm.genrcm to C/Fortran array" );
  } else {
    adj = (int *)(capi_adj_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = (len(adj_row)-1); else
    f2py_success = int_from_pyobj(&n,n_capi,"rcm.genrcm() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((len(adj_row)-1)>=n,"(len(adj_row)-1)>=n","1st keyword n","genrcm:n=%d",n) {
  /* Processing variable perm */
  perm_Dims[0]=n;
  capi_perm_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_perm_tmp = array_from_pyobj(PyArray_INT,perm_Dims,perm_Rank,capi_perm_intent,Py_None);
  if (capi_perm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `perm' of rcm.genrcm to C/Fortran array" );
  } else {
    perm = (int *)(capi_perm_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,adj_row,adj,perm);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_perm_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_perm_tmp == NULL) ... else of perm*/
  /* End of cleaning variable perm */
  } /*CHECKSCALAR((len(adj_row)-1)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_adj_tmp!=adj_capi) {
    Py_XDECREF(capi_adj_tmp); }
  }  /*if (capi_adj_tmp == NULL) ... else of adj*/
  /* End of cleaning variable adj */
  if((PyObject *)capi_adj_row_tmp!=adj_row_capi) {
    Py_XDECREF(capi_adj_row_tmp); }
  }  /*if (capi_adj_row_tmp == NULL) ... else of adj_row*/
  /* End of cleaning variable adj_row */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of genrcm *******************************/

/********************************* root_find *********************************/
static char doc_f2py_rout_rcm_root_find[] = "\
Function signature:\n\
  root,nlvl,xls,ls = root_find(root,adj_row,adj,mask,[n])\n\
Required arguments:\n"
"  root : input int\n"
"  adj_row : input rank-1 array('i') with bounds (n + 1)\n"
"  adj : input rank-1 array('i') with bounds (*)\n"
"  mask : input rank-1 array('i') with bounds (n)\n"
"Optional arguments:\n"
"  n := (len(adj_row)-1) input int\n"
"Return objects:\n"
"  root : int\n"
"  nlvl : int\n"
"  xls : rank-1 array('i') with bounds (n + 1)\n"
"  ls : rank-1 array('i') with bounds (n)";
/* extern void F_FUNC_US(root_find,ROOT_FIND)(int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_rcm_root_find(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int root = 0;
  PyObject *root_capi = Py_None;
  int *adj_row = NULL;
  npy_intp adj_row_Dims[1] = {-1};
  const int adj_row_Rank = 1;
  PyArrayObject *capi_adj_row_tmp = NULL;
  int capi_adj_row_intent = 0;
  PyObject *adj_row_capi = Py_None;
  int *adj = NULL;
  npy_intp adj_Dims[1] = {-1};
  const int adj_Rank = 1;
  PyArrayObject *capi_adj_tmp = NULL;
  int capi_adj_intent = 0;
  PyObject *adj_capi = Py_None;
  int *mask = NULL;
  npy_intp mask_Dims[1] = {-1};
  const int mask_Rank = 1;
  PyArrayObject *capi_mask_tmp = NULL;
  int capi_mask_intent = 0;
  PyObject *mask_capi = Py_None;
  int nlvl = 0;
  int *xls = NULL;
  npy_intp xls_Dims[1] = {-1};
  const int xls_Rank = 1;
  PyArrayObject *capi_xls_tmp = NULL;
  int capi_xls_intent = 0;
  int *ls = NULL;
  npy_intp ls_Dims[1] = {-1};
  const int ls_Rank = 1;
  PyArrayObject *capi_ls_tmp = NULL;
  int capi_ls_intent = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"root","adj_row","adj","mask","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:rcm.root_find",\
    capi_kwlist,&root_capi,&adj_row_capi,&adj_capi,&mask_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nlvl */
  /* Processing variable adj_row */
  ;
  capi_adj_row_intent |= F2PY_INTENT_IN;
  capi_adj_row_tmp = array_from_pyobj(PyArray_INT,adj_row_Dims,adj_row_Rank,capi_adj_row_intent,adj_row_capi);
  if (capi_adj_row_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 2nd argument `adj_row' of rcm.root_find to C/Fortran array" );
  } else {
    adj_row = (int *)(capi_adj_row_tmp->data);

  /* Processing variable root */
    f2py_success = int_from_pyobj(&root,root_capi,"rcm.root_find() 1st argument (root) can't be converted to int");
  if (f2py_success) {
  /* Processing variable adj */
  ;
  capi_adj_intent |= F2PY_INTENT_IN;
  capi_adj_tmp = array_from_pyobj(PyArray_INT,adj_Dims,adj_Rank,capi_adj_intent,adj_capi);
  if (capi_adj_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 3rd argument `adj' of rcm.root_find to C/Fortran array" );
  } else {
    adj = (int *)(capi_adj_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = (len(adj_row)-1); else
    f2py_success = int_from_pyobj(&n,n_capi,"rcm.root_find() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((len(adj_row)-1)>=n,"(len(adj_row)-1)>=n","1st keyword n","root_find:n=%d",n) {
  /* Processing variable ls */
  ls_Dims[0]=n;
  capi_ls_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ls_tmp = array_from_pyobj(PyArray_INT,ls_Dims,ls_Rank,capi_ls_intent,Py_None);
  if (capi_ls_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `ls' of rcm.root_find to C/Fortran array" );
  } else {
    ls = (int *)(capi_ls_tmp->data);

  /* Processing variable xls */
  xls_Dims[0]=n + 1;
  capi_xls_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_xls_tmp = array_from_pyobj(PyArray_INT,xls_Dims,xls_Rank,capi_xls_intent,Py_None);
  if (capi_xls_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `xls' of rcm.root_find to C/Fortran array" );
  } else {
    xls = (int *)(capi_xls_tmp->data);

  /* Processing variable mask */
  mask_Dims[0]=n;
  capi_mask_intent |= F2PY_INTENT_IN;
  capi_mask_tmp = array_from_pyobj(PyArray_INT,mask_Dims,mask_Rank,capi_mask_intent,mask_capi);
  if (capi_mask_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 4th argument `mask' of rcm.root_find to C/Fortran array" );
  } else {
    mask = (int *)(capi_mask_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&root,adj_row,adj,mask,&nlvl,xls,ls,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("iiNN",root,nlvl,capi_xls_tmp,capi_ls_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_mask_tmp!=mask_capi) {
    Py_XDECREF(capi_mask_tmp); }
  }  /*if (capi_mask_tmp == NULL) ... else of mask*/
  /* End of cleaning variable mask */
  }  /*if (capi_xls_tmp == NULL) ... else of xls*/
  /* End of cleaning variable xls */
  }  /*if (capi_ls_tmp == NULL) ... else of ls*/
  /* End of cleaning variable ls */
  } /*CHECKSCALAR((len(adj_row)-1)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_adj_tmp!=adj_capi) {
    Py_XDECREF(capi_adj_tmp); }
  }  /*if (capi_adj_tmp == NULL) ... else of adj*/
  /* End of cleaning variable adj */
  } /*if (f2py_success) of root*/
  /* End of cleaning variable root */
  if((PyObject *)capi_adj_row_tmp!=adj_row_capi) {
    Py_XDECREF(capi_adj_row_tmp); }
  }  /*if (capi_adj_row_tmp == NULL) ... else of adj_row*/
  /* End of cleaning variable adj_row */
  /* End of cleaning variable nlvl */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of root_find ******************************/

/********************************* level_set *********************************/
static char doc_f2py_rout_rcm_level_set[] = "\
Function signature:\n\
  mask,nlvl,xls,ls = level_set(root,adj_row,adj,mask,[n])\n\
Required arguments:\n"
"  root : input int\n"
"  adj_row : input rank-1 array('i') with bounds (n + 1)\n"
"  adj : input rank-1 array('i') with bounds (*)\n"
"  mask : input rank-1 array('i') with bounds (n)\n"
"Optional arguments:\n"
"  n := (len(adj_row)-1) input int\n"
"Return objects:\n"
"  mask : rank-1 array('i') with bounds (n)\n"
"  nlvl : int\n"
"  xls : rank-1 array('i') with bounds (n + 1)\n"
"  ls : rank-1 array('i') with bounds (n)";
/* extern void F_FUNC_US(level_set,LEVEL_SET)(int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_rcm_level_set(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int root = 0;
  PyObject *root_capi = Py_None;
  int *adj_row = NULL;
  npy_intp adj_row_Dims[1] = {-1};
  const int adj_row_Rank = 1;
  PyArrayObject *capi_adj_row_tmp = NULL;
  int capi_adj_row_intent = 0;
  PyObject *adj_row_capi = Py_None;
  int *adj = NULL;
  npy_intp adj_Dims[1] = {-1};
  const int adj_Rank = 1;
  PyArrayObject *capi_adj_tmp = NULL;
  int capi_adj_intent = 0;
  PyObject *adj_capi = Py_None;
  int *mask = NULL;
  npy_intp mask_Dims[1] = {-1};
  const int mask_Rank = 1;
  PyArrayObject *capi_mask_tmp = NULL;
  int capi_mask_intent = 0;
  PyObject *mask_capi = Py_None;
  int nlvl = 0;
  int *xls = NULL;
  npy_intp xls_Dims[1] = {-1};
  const int xls_Rank = 1;
  PyArrayObject *capi_xls_tmp = NULL;
  int capi_xls_intent = 0;
  int *ls = NULL;
  npy_intp ls_Dims[1] = {-1};
  const int ls_Rank = 1;
  PyArrayObject *capi_ls_tmp = NULL;
  int capi_ls_intent = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"root","adj_row","adj","mask","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:rcm.level_set",\
    capi_kwlist,&root_capi,&adj_row_capi,&adj_capi,&mask_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nlvl */
  /* Processing variable adj_row */
  ;
  capi_adj_row_intent |= F2PY_INTENT_IN;
  capi_adj_row_tmp = array_from_pyobj(PyArray_INT,adj_row_Dims,adj_row_Rank,capi_adj_row_intent,adj_row_capi);
  if (capi_adj_row_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 2nd argument `adj_row' of rcm.level_set to C/Fortran array" );
  } else {
    adj_row = (int *)(capi_adj_row_tmp->data);

  /* Processing variable root */
    f2py_success = int_from_pyobj(&root,root_capi,"rcm.level_set() 1st argument (root) can't be converted to int");
  if (f2py_success) {
  /* Processing variable adj */
  ;
  capi_adj_intent |= F2PY_INTENT_IN;
  capi_adj_tmp = array_from_pyobj(PyArray_INT,adj_Dims,adj_Rank,capi_adj_intent,adj_capi);
  if (capi_adj_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 3rd argument `adj' of rcm.level_set to C/Fortran array" );
  } else {
    adj = (int *)(capi_adj_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = (len(adj_row)-1); else
    f2py_success = int_from_pyobj(&n,n_capi,"rcm.level_set() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((len(adj_row)-1)>=n,"(len(adj_row)-1)>=n","1st keyword n","level_set:n=%d",n) {
  /* Processing variable ls */
  ls_Dims[0]=n;
  capi_ls_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ls_tmp = array_from_pyobj(PyArray_INT,ls_Dims,ls_Rank,capi_ls_intent,Py_None);
  if (capi_ls_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `ls' of rcm.level_set to C/Fortran array" );
  } else {
    ls = (int *)(capi_ls_tmp->data);

  /* Processing variable xls */
  xls_Dims[0]=n + 1;
  capi_xls_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_xls_tmp = array_from_pyobj(PyArray_INT,xls_Dims,xls_Rank,capi_xls_intent,Py_None);
  if (capi_xls_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `xls' of rcm.level_set to C/Fortran array" );
  } else {
    xls = (int *)(capi_xls_tmp->data);

  /* Processing variable mask */
  mask_Dims[0]=n;
  capi_mask_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_mask_tmp = array_from_pyobj(PyArray_INT,mask_Dims,mask_Rank,capi_mask_intent,mask_capi);
  if (capi_mask_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 4th argument `mask' of rcm.level_set to C/Fortran array" );
  } else {
    mask = (int *)(capi_mask_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&root,adj_row,adj,mask,&nlvl,xls,ls,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NiNN",capi_mask_tmp,nlvl,capi_xls_tmp,capi_ls_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_mask_tmp == NULL) ... else of mask*/
  /* End of cleaning variable mask */
  }  /*if (capi_xls_tmp == NULL) ... else of xls*/
  /* End of cleaning variable xls */
  }  /*if (capi_ls_tmp == NULL) ... else of ls*/
  /* End of cleaning variable ls */
  } /*CHECKSCALAR((len(adj_row)-1)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_adj_tmp!=adj_capi) {
    Py_XDECREF(capi_adj_tmp); }
  }  /*if (capi_adj_tmp == NULL) ... else of adj*/
  /* End of cleaning variable adj */
  } /*if (f2py_success) of root*/
  /* End of cleaning variable root */
  if((PyObject *)capi_adj_row_tmp!=adj_row_capi) {
    Py_XDECREF(capi_adj_row_tmp); }
  }  /*if (capi_adj_row_tmp == NULL) ... else of adj_row*/
  /* End of cleaning variable adj_row */
  /* End of cleaning variable nlvl */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of level_set ******************************/

/************************************ rcm ************************************/
static char doc_f2py_rout_rcm_rcm[] = "\
Function signature:\n\
  mask,perm,iccsze = rcm(root,adj_row,adj,mask,[n])\n\
Required arguments:\n"
"  root : input int\n"
"  adj_row : input rank-1 array('i') with bounds (n + 1)\n"
"  adj : input rank-1 array('i') with bounds (*)\n"
"  mask : input rank-1 array('i') with bounds (n)\n"
"Optional arguments:\n"
"  n := (len(adj_row)-1) input int\n"
"Return objects:\n"
"  mask : rank-1 array('i') with bounds (n)\n"
"  perm : rank-1 array('i') with bounds (n)\n"
"  iccsze : int";
/* extern void F_FUNC(rcm,RCM)(int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_rcm_rcm(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int root = 0;
  PyObject *root_capi = Py_None;
  int *adj_row = NULL;
  npy_intp adj_row_Dims[1] = {-1};
  const int adj_row_Rank = 1;
  PyArrayObject *capi_adj_row_tmp = NULL;
  int capi_adj_row_intent = 0;
  PyObject *adj_row_capi = Py_None;
  int *adj = NULL;
  npy_intp adj_Dims[1] = {-1};
  const int adj_Rank = 1;
  PyArrayObject *capi_adj_tmp = NULL;
  int capi_adj_intent = 0;
  PyObject *adj_capi = Py_None;
  int *mask = NULL;
  npy_intp mask_Dims[1] = {-1};
  const int mask_Rank = 1;
  PyArrayObject *capi_mask_tmp = NULL;
  int capi_mask_intent = 0;
  PyObject *mask_capi = Py_None;
  int *perm = NULL;
  npy_intp perm_Dims[1] = {-1};
  const int perm_Rank = 1;
  PyArrayObject *capi_perm_tmp = NULL;
  int capi_perm_intent = 0;
  int iccsze = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"root","adj_row","adj","mask","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:rcm.rcm",\
    capi_kwlist,&root_capi,&adj_row_capi,&adj_capi,&mask_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable root */
    f2py_success = int_from_pyobj(&root,root_capi,"rcm.rcm() 1st argument (root) can't be converted to int");
  if (f2py_success) {
  /* Processing variable adj */
  ;
  capi_adj_intent |= F2PY_INTENT_IN;
  capi_adj_tmp = array_from_pyobj(PyArray_INT,adj_Dims,adj_Rank,capi_adj_intent,adj_capi);
  if (capi_adj_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 3rd argument `adj' of rcm.rcm to C/Fortran array" );
  } else {
    adj = (int *)(capi_adj_tmp->data);

  /* Processing variable iccsze */
  /* Processing variable adj_row */
  ;
  capi_adj_row_intent |= F2PY_INTENT_IN;
  capi_adj_row_tmp = array_from_pyobj(PyArray_INT,adj_row_Dims,adj_row_Rank,capi_adj_row_intent,adj_row_capi);
  if (capi_adj_row_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 2nd argument `adj_row' of rcm.rcm to C/Fortran array" );
  } else {
    adj_row = (int *)(capi_adj_row_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = (len(adj_row)-1); else
    f2py_success = int_from_pyobj(&n,n_capi,"rcm.rcm() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((len(adj_row)-1)>=n,"(len(adj_row)-1)>=n","1st keyword n","rcm:n=%d",n) {
  /* Processing variable mask */
  mask_Dims[0]=n;
  capi_mask_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_mask_tmp = array_from_pyobj(PyArray_INT,mask_Dims,mask_Rank,capi_mask_intent,mask_capi);
  if (capi_mask_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 4th argument `mask' of rcm.rcm to C/Fortran array" );
  } else {
    mask = (int *)(capi_mask_tmp->data);

  /* Processing variable perm */
  perm_Dims[0]=n;
  capi_perm_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_perm_tmp = array_from_pyobj(PyArray_INT,perm_Dims,perm_Rank,capi_perm_intent,Py_None);
  if (capi_perm_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `perm' of rcm.rcm to C/Fortran array" );
  } else {
    perm = (int *)(capi_perm_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&root,adj_row,adj,mask,perm,&iccsze,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNi",capi_mask_tmp,capi_perm_tmp,iccsze);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_perm_tmp == NULL) ... else of perm*/
  /* End of cleaning variable perm */
  }  /*if (capi_mask_tmp == NULL) ... else of mask*/
  /* End of cleaning variable mask */
  } /*CHECKSCALAR((len(adj_row)-1)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_adj_row_tmp!=adj_row_capi) {
    Py_XDECREF(capi_adj_row_tmp); }
  }  /*if (capi_adj_row_tmp == NULL) ... else of adj_row*/
  /* End of cleaning variable adj_row */
  /* End of cleaning variable iccsze */
  if((PyObject *)capi_adj_tmp!=adj_capi) {
    Py_XDECREF(capi_adj_tmp); }
  }  /*if (capi_adj_tmp == NULL) ... else of adj*/
  /* End of cleaning variable adj */
  } /*if (f2py_success) of root*/
  /* End of cleaning variable root */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/********************************* end of rcm *********************************/

/*********************************** degree ***********************************/
static char doc_f2py_rout_rcm_degree[] = "\
Function signature:\n\
  deg,iccsze,ls = degree(root,adj_row,adj,mask,[n])\n\
Required arguments:\n"
"  root : input int\n"
"  adj_row : input rank-1 array('i') with bounds (n + 1)\n"
"  adj : input rank-1 array('i') with bounds (*)\n"
"  mask : input rank-1 array('i') with bounds (n)\n"
"Optional arguments:\n"
"  n := (len(adj_row)-1) input int\n"
"Return objects:\n"
"  deg : rank-1 array('i') with bounds (n)\n"
"  iccsze : int\n"
"  ls : rank-1 array('i') with bounds (n)";
/* extern void F_FUNC(degree,DEGREE)(int*,int*,int*,int*,int*,int*,int*,int*); */
static PyObject *f2py_rout_rcm_degree(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int root = 0;
  PyObject *root_capi = Py_None;
  int *adj_row = NULL;
  npy_intp adj_row_Dims[1] = {-1};
  const int adj_row_Rank = 1;
  PyArrayObject *capi_adj_row_tmp = NULL;
  int capi_adj_row_intent = 0;
  PyObject *adj_row_capi = Py_None;
  int *adj = NULL;
  npy_intp adj_Dims[1] = {-1};
  const int adj_Rank = 1;
  PyArrayObject *capi_adj_tmp = NULL;
  int capi_adj_intent = 0;
  PyObject *adj_capi = Py_None;
  int *mask = NULL;
  npy_intp mask_Dims[1] = {-1};
  const int mask_Rank = 1;
  PyArrayObject *capi_mask_tmp = NULL;
  int capi_mask_intent = 0;
  PyObject *mask_capi = Py_None;
  int *deg = NULL;
  npy_intp deg_Dims[1] = {-1};
  const int deg_Rank = 1;
  PyArrayObject *capi_deg_tmp = NULL;
  int capi_deg_intent = 0;
  int iccsze = 0;
  int *ls = NULL;
  npy_intp ls_Dims[1] = {-1};
  const int ls_Rank = 1;
  PyArrayObject *capi_ls_tmp = NULL;
  int capi_ls_intent = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"root","adj_row","adj","mask","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO|O:rcm.degree",\
    capi_kwlist,&root_capi,&adj_row_capi,&adj_capi,&mask_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iccsze */
  /* Processing variable adj_row */
  ;
  capi_adj_row_intent |= F2PY_INTENT_IN;
  capi_adj_row_tmp = array_from_pyobj(PyArray_INT,adj_row_Dims,adj_row_Rank,capi_adj_row_intent,adj_row_capi);
  if (capi_adj_row_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 2nd argument `adj_row' of rcm.degree to C/Fortran array" );
  } else {
    adj_row = (int *)(capi_adj_row_tmp->data);

  /* Processing variable root */
    f2py_success = int_from_pyobj(&root,root_capi,"rcm.degree() 1st argument (root) can't be converted to int");
  if (f2py_success) {
  /* Processing variable adj */
  ;
  capi_adj_intent |= F2PY_INTENT_IN;
  capi_adj_tmp = array_from_pyobj(PyArray_INT,adj_Dims,adj_Rank,capi_adj_intent,adj_capi);
  if (capi_adj_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 3rd argument `adj' of rcm.degree to C/Fortran array" );
  } else {
    adj = (int *)(capi_adj_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = (len(adj_row)-1); else
    f2py_success = int_from_pyobj(&n,n_capi,"rcm.degree() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR((len(adj_row)-1)>=n,"(len(adj_row)-1)>=n","1st keyword n","degree:n=%d",n) {
  /* Processing variable ls */
  ls_Dims[0]=n;
  capi_ls_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_ls_tmp = array_from_pyobj(PyArray_INT,ls_Dims,ls_Rank,capi_ls_intent,Py_None);
  if (capi_ls_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `ls' of rcm.degree to C/Fortran array" );
  } else {
    ls = (int *)(capi_ls_tmp->data);

  /* Processing variable deg */
  deg_Dims[0]=n;
  capi_deg_intent |= F2PY_INTENT_HIDE|F2PY_INTENT_OUT;
  capi_deg_tmp = array_from_pyobj(PyArray_INT,deg_Dims,deg_Rank,capi_deg_intent,Py_None);
  if (capi_deg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting hidden `deg' of rcm.degree to C/Fortran array" );
  } else {
    deg = (int *)(capi_deg_tmp->data);

  /* Processing variable mask */
  mask_Dims[0]=n;
  capi_mask_intent |= F2PY_INTENT_IN;
  capi_mask_tmp = array_from_pyobj(PyArray_INT,mask_Dims,mask_Rank,capi_mask_intent,mask_capi);
  if (capi_mask_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 4th argument `mask' of rcm.degree to C/Fortran array" );
  } else {
    mask = (int *)(capi_mask_tmp->data);

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&root,adj_row,adj,mask,deg,&iccsze,ls,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NiN",capi_deg_tmp,iccsze,capi_ls_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_mask_tmp!=mask_capi) {
    Py_XDECREF(capi_mask_tmp); }
  }  /*if (capi_mask_tmp == NULL) ... else of mask*/
  /* End of cleaning variable mask */
  }  /*if (capi_deg_tmp == NULL) ... else of deg*/
  /* End of cleaning variable deg */
  }  /*if (capi_ls_tmp == NULL) ... else of ls*/
  /* End of cleaning variable ls */
  } /*CHECKSCALAR((len(adj_row)-1)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_adj_tmp!=adj_capi) {
    Py_XDECREF(capi_adj_tmp); }
  }  /*if (capi_adj_tmp == NULL) ... else of adj*/
  /* End of cleaning variable adj */
  } /*if (f2py_success) of root*/
  /* End of cleaning variable root */
  if((PyObject *)capi_adj_row_tmp!=adj_row_capi) {
    Py_XDECREF(capi_adj_row_tmp); }
  }  /*if (capi_adj_row_tmp == NULL) ... else of adj_row*/
  /* End of cleaning variable adj_row */
  /* End of cleaning variable iccsze */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of degree *******************************/

/******************************** ivec_reverse ********************************/
static char doc_f2py_rout_rcm_ivec_reverse[] = "\
Function signature:\n\
  a = ivec_reverse(a,[n])\n\
Required arguments:\n"
"  a : input rank-1 array('i') with bounds (n)\n"
"Optional arguments:\n"
"  n := len(a) input int\n"
"Return objects:\n"
"  a : rank-1 array('i') with bounds (n)";
/* extern void F_FUNC_US(ivec_reverse,IVEC_REVERSE)(int*,int*); */
static PyObject *f2py_rout_rcm_ivec_reverse(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  int *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  static char *capi_kwlist[] = {"a","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|O:rcm.ivec_reverse",\
    capi_kwlist,&a_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable a */
  ;
  capi_a_intent |= F2PY_INTENT_OUT|F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_INT,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(rcm_error,"failed in converting 1st argument `a' of rcm.ivec_reverse to C/Fortran array" );
  } else {
    a = (int *)(capi_a_tmp->data);

  /* Processing variable n */
  if (n_capi == Py_None) n = len(a); else
    f2py_success = int_from_pyobj(&n,n_capi,"rcm.ivec_reverse() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(a)>=n,"len(a)>=n","1st keyword n","ivec_reverse:n=%d",n) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&n,a);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_a_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*CHECKSCALAR(len(a)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of ivec_reverse ****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"genrcm",-1,{{-1}},0,(char *)F_FUNC(genrcm,GENRCM),(f2py_init_func)f2py_rout_rcm_genrcm,doc_f2py_rout_rcm_genrcm},
  {"root_find",-1,{{-1}},0,(char *)F_FUNC_US(root_find,ROOT_FIND),(f2py_init_func)f2py_rout_rcm_root_find,doc_f2py_rout_rcm_root_find},
  {"level_set",-1,{{-1}},0,(char *)F_FUNC_US(level_set,LEVEL_SET),(f2py_init_func)f2py_rout_rcm_level_set,doc_f2py_rout_rcm_level_set},
  {"rcm",-1,{{-1}},0,(char *)F_FUNC(rcm,RCM),(f2py_init_func)f2py_rout_rcm_rcm,doc_f2py_rout_rcm_rcm},
  {"degree",-1,{{-1}},0,(char *)F_FUNC(degree,DEGREE),(f2py_init_func)f2py_rout_rcm_degree,doc_f2py_rout_rcm_degree},
  {"ivec_reverse",-1,{{-1}},0,(char *)F_FUNC_US(ivec_reverse,IVEC_REVERSE),(f2py_init_func)f2py_rout_rcm_ivec_reverse,doc_f2py_rout_rcm_ivec_reverse},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initrcm(void) {
  int i;
  PyObject *m,*d, *s;
  m = rcm_module = Py_InitModule("rcm", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module rcm (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'rcm' is auto-generated with f2py (version:2_5237).\nFunctions:\n"
"  perm = genrcm(adj_row,adj,n=(len(adj_row)-1))\n"
"  root,nlvl,xls,ls = root_find(root,adj_row,adj,mask,n=(len(adj_row)-1))\n"
"  mask,nlvl,xls,ls = level_set(root,adj_row,adj,mask,n=(len(adj_row)-1))\n"
"  mask,perm,iccsze = rcm(root,adj_row,adj,mask,n=(len(adj_row)-1))\n"
"  deg,iccsze,ls = degree(root,adj_row,adj,mask,n=(len(adj_row)-1))\n"
"  a = ivec_reverse(a,n=len(a))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  rcm_error = PyErr_NewException ("rcm.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));






/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"rcm");
#endif

}
#ifdef __cplusplus
}
#endif
