/* File: sparslabmodule.c
 * This file is auto-generated with f2py (version:2_5237).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Tue Oct 27 11:51:19 2009
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *sparslab_error;
static PyObject *sparslab_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define max(a,b) ((a > b) ? (a) : (b))
#define min(a,b) ((a < b) ? (a) : (b))
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = sparslab_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyFloat_Check(obj)) {
#ifdef __sgi
    *v = PyFloat_AsDouble(obj);
#else
    *v = PyFloat_AS_DOUBLE(obj);
#endif
    return 1;
  }
  tmp = PyNumber_Float(obj);
  if (tmp) {
#ifdef __sgi
    *v = PyFloat_AsDouble(tmp);
#else
    *v = PyFloat_AS_DOUBLE(tmp);
#endif
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = sparslab_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** ainvsr2 **********************************/
static char doc_f2py_rout_sparslab_ainvsr2module_ainvsr2[] = "\
Function signature:\n\
  size_p,size_c,size_r,fill,fillmax,garrow,garcol,info = ainvsr2(ia,ja,a,[msglvl,msgunit,size_p,size_c,size_r,diagtol,drfl,mi,diag_one,droptyp,imodif,fill,fillmax,ifillmax])\n\
Required arguments:\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  a : input rank-1 array('d') with bounds (len(ja))\n"
"Optional arguments:\n"
"  msglvl := 2 input int\n"
"  msgunit := 2 input int\n"
"  size_p := 1000000 input int\n"
"  size_c := 1000000 input int\n"
"  size_r := 1000000 input int\n"
"  diagtol := 1.1e-16 input float\n"
"  drfl := 1e-06 input float\n"
"  mi := 0.1 input float\n"
"  diag_one := 1 input int\n"
"  droptyp := 0 input int\n"
"  imodif := 0 input int\n"
"  fill := fillmax input int\n"
"  fillmax := n*n input int\n"
"  ifillmax := 0 input int\n"
"Return objects:\n"
"  size_p : int\n"
"  size_c : int\n"
"  size_r : int\n"
"  fill : int\n"
"  fillmax : int\n"
"  garrow : int\n"
"  garcol : int\n"
"  info : int";
/*  */
static PyObject *f2py_rout_sparslab_ainvsr2module_ainvsr2(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int msglvl = 0;
  PyObject *msglvl_capi = Py_None;
  int msgunit = 0;
  PyObject *msgunit_capi = Py_None;
  int n = 0;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int size_p = 0;
  PyObject *size_p_capi = Py_None;
  int size_c = 0;
  PyObject *size_c_capi = Py_None;
  int size_r = 0;
  PyObject *size_r_capi = Py_None;
  double diagtol = 0;
  PyObject *diagtol_capi = Py_None;
  double drfl = 0;
  PyObject *drfl_capi = Py_None;
  double mi = 0;
  PyObject *mi_capi = Py_None;
  int diag_one = 0;
  PyObject *diag_one_capi = Py_None;
  int droptyp = 0;
  PyObject *droptyp_capi = Py_None;
  int imodif = 0;
  PyObject *imodif_capi = Py_None;
  int fill = 0;
  PyObject *fill_capi = Py_None;
  int fillmax = 0;
  PyObject *fillmax_capi = Py_None;
  int ifillmax = 0;
  PyObject *ifillmax_capi = Py_None;
  int garrow = 0;
  int garcol = 0;
  int info = 0;
  static char *capi_kwlist[] = {"ia","ja","a","msglvl","msgunit","size_p","size_c","size_r","diagtol","drfl","mi","diag_one","droptyp","imodif","fill","fillmax","ifillmax",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOOOOOOOOOOOOO:sparslab.ainvsr2module.ainvsr2",\
    capi_kwlist,&ia_capi,&ja_capi,&a_capi,&msglvl_capi,&msgunit_capi,&size_p_capi,&size_c_capi,&size_r_capi,&diagtol_capi,&drfl_capi,&mi_capi,&diag_one_capi,&droptyp_capi,&imodif_capi,&fill_capi,&fillmax_capi,&ifillmax_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable info */
  /* Processing variable garrow */
  /* Processing variable droptyp */
  if (droptyp_capi == Py_None) droptyp = 0; else
    f2py_success = int_from_pyobj(&droptyp,droptyp_capi,"sparslab.ainvsr2module.ainvsr2() 10th keyword (droptyp) can't be converted to int");
  if (f2py_success) {
  /* Processing variable diagtol */
  if (diagtol_capi == Py_None) diagtol = 1.1e-16; else
    f2py_success = double_from_pyobj(&diagtol,diagtol_capi,"sparslab.ainvsr2module.ainvsr2() 6th keyword (diagtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ifillmax */
  if (ifillmax_capi == Py_None) ifillmax = 0; else
    f2py_success = int_from_pyobj(&ifillmax,ifillmax_capi,"sparslab.ainvsr2module.ainvsr2() 14th keyword (ifillmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable size_c */
  if (size_c_capi == Py_None) size_c = 1000000; else
    f2py_success = int_from_pyobj(&size_c,size_c_capi,"sparslab.ainvsr2module.ainvsr2() 4th keyword (size_c) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sparslab_error,"failed in converting 1st argument `ia' of sparslab.ainvsr2module.ainvsr2 to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable size_p */
  if (size_p_capi == Py_None) size_p = 1000000; else
    f2py_success = int_from_pyobj(&size_p,size_p_capi,"sparslab.ainvsr2module.ainvsr2() 3rd keyword (size_p) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sparslab_error,"failed in converting 2nd argument `ja' of sparslab.ainvsr2module.ainvsr2 to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable size_r */
  if (size_r_capi == Py_None) size_r = 1000000; else
    f2py_success = int_from_pyobj(&size_r,size_r_capi,"sparslab.ainvsr2module.ainvsr2() 5th keyword (size_r) can't be converted to int");
  if (f2py_success) {
  /* Processing variable drfl */
  if (drfl_capi == Py_None) drfl = 1e-06; else
    f2py_success = double_from_pyobj(&drfl,drfl_capi,"sparslab.ainvsr2module.ainvsr2() 7th keyword (drfl) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mi */
  if (mi_capi == Py_None) mi = 0.1; else
    f2py_success = double_from_pyobj(&mi,mi_capi,"sparslab.ainvsr2module.ainvsr2() 8th keyword (mi) can't be converted to double");
  if (f2py_success) {
  /* Processing variable imodif */
  if (imodif_capi == Py_None) imodif = 0; else
    f2py_success = int_from_pyobj(&imodif,imodif_capi,"sparslab.ainvsr2module.ainvsr2() 11st keyword (imodif) can't be converted to int");
  if (f2py_success) {
  /* Processing variable msgunit */
  if (msgunit_capi == Py_None) msgunit = 2; else
    f2py_success = int_from_pyobj(&msgunit,msgunit_capi,"sparslab.ainvsr2module.ainvsr2() 2nd keyword (msgunit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable garcol */
  /* Processing variable msglvl */
  if (msglvl_capi == Py_None) msglvl = 2; else
    f2py_success = int_from_pyobj(&msglvl,msglvl_capi,"sparslab.ainvsr2module.ainvsr2() 1st keyword (msglvl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable diag_one */
  if (diag_one_capi == Py_None) diag_one = 1; else
    f2py_success = int_from_pyobj(&diag_one,diag_one_capi,"sparslab.ainvsr2module.ainvsr2() 9th keyword (diag_one) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
  n = len(ia)-1;
  /* Processing variable a */
  a_Dims[0]=len(ja);
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sparslab_error,"failed in converting 3rd argument `a' of sparslab.ainvsr2module.ainvsr2 to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable fillmax */
  if (fillmax_capi == Py_None) fillmax = n*n; else
    f2py_success = int_from_pyobj(&fillmax,fillmax_capi,"sparslab.ainvsr2module.ainvsr2() 13rd keyword (fillmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable fill */
  if (fill_capi == Py_None) fill = fillmax; else
    f2py_success = int_from_pyobj(&fill,fill_capi,"sparslab.ainvsr2module.ainvsr2() 12nd keyword (fill) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&msglvl,&msgunit,&n,ia,ja,a,&size_p,&size_c,&size_r,&diagtol,&drfl,&mi,&diag_one,&droptyp,&imodif,&fill,&fillmax,&ifillmax,&garrow,&garcol,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("iiiiiiii",size_p,size_c,size_r,fill,fillmax,garrow,garcol,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of fill*/
  /* End of cleaning variable fill */
  } /*if (f2py_success) of fillmax*/
  /* End of cleaning variable fillmax */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  /* End of cleaning variable n */
  } /*if (f2py_success) of diag_one*/
  /* End of cleaning variable diag_one */
  } /*if (f2py_success) of msglvl*/
  /* End of cleaning variable msglvl */
  /* End of cleaning variable garcol */
  } /*if (f2py_success) of msgunit*/
  /* End of cleaning variable msgunit */
  } /*if (f2py_success) of imodif*/
  /* End of cleaning variable imodif */
  } /*if (f2py_success) of mi*/
  /* End of cleaning variable mi */
  } /*if (f2py_success) of drfl*/
  /* End of cleaning variable drfl */
  } /*if (f2py_success) of size_r*/
  /* End of cleaning variable size_r */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  } /*if (f2py_success) of size_p*/
  /* End of cleaning variable size_p */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  } /*if (f2py_success) of size_c*/
  /* End of cleaning variable size_c */
  } /*if (f2py_success) of ifillmax*/
  /* End of cleaning variable ifillmax */
  } /*if (f2py_success) of diagtol*/
  /* End of cleaning variable diagtol */
  } /*if (f2py_success) of droptyp*/
  /* End of cleaning variable droptyp */
  /* End of cleaning variable garrow */
  /* End of cleaning variable info */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of ainvsr2 *******************************/

/*********************************** rifsr ***********************************/
static char doc_f2py_rout_sparslab_rifsrmodule_rifsr[] = "\
Function signature:\n\
  size_c,size_r,size_p,imodif,filldyn,fillmax,ifillmax,garrow,garcol,fillic,info = rifsr(ia,ja,a,[msglvl,msgunit,size_c,size_r,size_p,diagtol,drflic,drflai,mi])\n\
Required arguments:\n"
"  ia : input rank-1 array('i') with bounds (*)\n"
"  ja : input rank-1 array('i') with bounds (*)\n"
"  a : input rank-1 array('d') with bounds (len(ja))\n"
"Optional arguments:\n"
"  msglvl := 2 input int\n"
"  msgunit := 2 input int\n"
"  size_c := 1000000 input int\n"
"  size_r := 1000000 input int\n"
"  size_p := 1000000 input int\n"
"  diagtol := 1.1e-16 input float\n"
"  drflic := 0.1 input float\n"
"  drflai := 0.1 input float\n"
"  mi := 0.1 input float\n"
"Return objects:\n"
"  size_c : int\n"
"  size_r : int\n"
"  size_p : int\n"
"  imodif : int\n"
"  filldyn : int\n"
"  fillmax : int\n"
"  ifillmax : int\n"
"  garrow : int\n"
"  garcol : int\n"
"  fillic : int\n"
"  info : int";
/*  */
static PyObject *f2py_rout_sparslab_rifsrmodule_rifsr(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,double*,int*,int*,int*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int msglvl = 0;
  PyObject *msglvl_capi = Py_None;
  int msgunit = 0;
  PyObject *msgunit_capi = Py_None;
  int n = 0;
  int *ia = NULL;
  npy_intp ia_Dims[1] = {-1};
  const int ia_Rank = 1;
  PyArrayObject *capi_ia_tmp = NULL;
  int capi_ia_intent = 0;
  PyObject *ia_capi = Py_None;
  int *ja = NULL;
  npy_intp ja_Dims[1] = {-1};
  const int ja_Rank = 1;
  PyArrayObject *capi_ja_tmp = NULL;
  int capi_ja_intent = 0;
  PyObject *ja_capi = Py_None;
  double *a = NULL;
  npy_intp a_Dims[1] = {-1};
  const int a_Rank = 1;
  PyArrayObject *capi_a_tmp = NULL;
  int capi_a_intent = 0;
  PyObject *a_capi = Py_None;
  int size_c = 0;
  PyObject *size_c_capi = Py_None;
  int size_r = 0;
  PyObject *size_r_capi = Py_None;
  int size_p = 0;
  PyObject *size_p_capi = Py_None;
  double diagtol = 0;
  PyObject *diagtol_capi = Py_None;
  double drflic = 0;
  PyObject *drflic_capi = Py_None;
  double drflai = 0;
  PyObject *drflai_capi = Py_None;
  double mi = 0;
  PyObject *mi_capi = Py_None;
  int diag_one = 0;
  int droptyp = 0;
  int imodif = 0;
  int filldyn = 0;
  int fillmax = 0;
  int ifillmax = 0;
  int garrow = 0;
  int garcol = 0;
  int fillic = 0;
  int info = 0;
  static char *capi_kwlist[] = {"ia","ja","a","msglvl","msgunit","size_c","size_r","size_p","diagtol","drflic","drflai","mi",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OOOOOOOOO:sparslab.rifsrmodule.rifsr",\
    capi_kwlist,&ia_capi,&ja_capi,&a_capi,&msglvl_capi,&msgunit_capi,&size_c_capi,&size_r_capi,&size_p_capi,&diagtol_capi,&drflic_capi,&drflai_capi,&mi_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable fillmax */
  /* Processing variable droptyp */
  droptyp = 0;
  /* Processing variable garrow */
  /* Processing variable drflic */
  if (drflic_capi == Py_None) drflic = 0.1; else
    f2py_success = double_from_pyobj(&drflic,drflic_capi,"sparslab.rifsrmodule.rifsr() 7th keyword (drflic) can't be converted to double");
  if (f2py_success) {
  /* Processing variable msglvl */
  if (msglvl_capi == Py_None) msglvl = 2; else
    f2py_success = int_from_pyobj(&msglvl,msglvl_capi,"sparslab.rifsrmodule.rifsr() 1st keyword (msglvl) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifillmax */
  /* Processing variable fillic */
  /* Processing variable size_c */
  if (size_c_capi == Py_None) size_c = 1000000; else
    f2py_success = int_from_pyobj(&size_c,size_c_capi,"sparslab.rifsrmodule.rifsr() 3rd keyword (size_c) can't be converted to int");
  if (f2py_success) {
  /* Processing variable drflai */
  if (drflai_capi == Py_None) drflai = 0.1; else
    f2py_success = double_from_pyobj(&drflai,drflai_capi,"sparslab.rifsrmodule.rifsr() 8th keyword (drflai) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ia */
  ;
  capi_ia_intent |= F2PY_INTENT_IN;
  capi_ia_tmp = array_from_pyobj(PyArray_INT,ia_Dims,ia_Rank,capi_ia_intent,ia_capi);
  if (capi_ia_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sparslab_error,"failed in converting 1st argument `ia' of sparslab.rifsrmodule.rifsr to C/Fortran array" );
  } else {
    ia = (int *)(capi_ia_tmp->data);

  /* Processing variable filldyn */
  /* Processing variable size_p */
  if (size_p_capi == Py_None) size_p = 1000000; else
    f2py_success = int_from_pyobj(&size_p,size_p_capi,"sparslab.rifsrmodule.rifsr() 5th keyword (size_p) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ja */
  ;
  capi_ja_intent |= F2PY_INTENT_IN;
  capi_ja_tmp = array_from_pyobj(PyArray_INT,ja_Dims,ja_Rank,capi_ja_intent,ja_capi);
  if (capi_ja_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sparslab_error,"failed in converting 2nd argument `ja' of sparslab.rifsrmodule.rifsr to C/Fortran array" );
  } else {
    ja = (int *)(capi_ja_tmp->data);

  /* Processing variable size_r */
  if (size_r_capi == Py_None) size_r = 1000000; else
    f2py_success = int_from_pyobj(&size_r,size_r_capi,"sparslab.rifsrmodule.rifsr() 4th keyword (size_r) can't be converted to int");
  if (f2py_success) {
  /* Processing variable imodif */
  /* Processing variable mi */
  if (mi_capi == Py_None) mi = 0.1; else
    f2py_success = double_from_pyobj(&mi,mi_capi,"sparslab.rifsrmodule.rifsr() 9th keyword (mi) can't be converted to double");
  if (f2py_success) {
  /* Processing variable info */
  /* Processing variable msgunit */
  if (msgunit_capi == Py_None) msgunit = 2; else
    f2py_success = int_from_pyobj(&msgunit,msgunit_capi,"sparslab.rifsrmodule.rifsr() 2nd keyword (msgunit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable garcol */
  /* Processing variable diagtol */
  if (diagtol_capi == Py_None) diagtol = 1.1e-16; else
    f2py_success = double_from_pyobj(&diagtol,diagtol_capi,"sparslab.rifsrmodule.rifsr() 6th keyword (diagtol) can't be converted to double");
  if (f2py_success) {
  /* Processing variable diag_one */
  diag_one = 1;
  /* Processing variable a */
  a_Dims[0]=len(ja);
  capi_a_intent |= F2PY_INTENT_IN;
  capi_a_tmp = array_from_pyobj(PyArray_DOUBLE,a_Dims,a_Rank,capi_a_intent,a_capi);
  if (capi_a_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(sparslab_error,"failed in converting 3rd argument `a' of sparslab.rifsrmodule.rifsr to C/Fortran array" );
  } else {
    a = (double *)(capi_a_tmp->data);

  /* Processing variable n */
  n = len(ia)-1;
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&msglvl,&msgunit,&n,ia,ja,a,&size_c,&size_r,&size_p,&diagtol,&drflic,&drflai,&mi,&diag_one,&droptyp,&imodif,&filldyn,&fillmax,&ifillmax,&garrow,&garcol,&fillic,&info);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("iiiiiiiiiii",size_c,size_r,size_p,imodif,filldyn,fillmax,ifillmax,garrow,garcol,fillic,info);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable n */
  if((PyObject *)capi_a_tmp!=a_capi) {
    Py_XDECREF(capi_a_tmp); }
  }  /*if (capi_a_tmp == NULL) ... else of a*/
  /* End of cleaning variable a */
  /* End of cleaning variable diag_one */
  } /*if (f2py_success) of diagtol*/
  /* End of cleaning variable diagtol */
  /* End of cleaning variable garcol */
  } /*if (f2py_success) of msgunit*/
  /* End of cleaning variable msgunit */
  /* End of cleaning variable info */
  } /*if (f2py_success) of mi*/
  /* End of cleaning variable mi */
  /* End of cleaning variable imodif */
  } /*if (f2py_success) of size_r*/
  /* End of cleaning variable size_r */
  if((PyObject *)capi_ja_tmp!=ja_capi) {
    Py_XDECREF(capi_ja_tmp); }
  }  /*if (capi_ja_tmp == NULL) ... else of ja*/
  /* End of cleaning variable ja */
  } /*if (f2py_success) of size_p*/
  /* End of cleaning variable size_p */
  /* End of cleaning variable filldyn */
  if((PyObject *)capi_ia_tmp!=ia_capi) {
    Py_XDECREF(capi_ia_tmp); }
  }  /*if (capi_ia_tmp == NULL) ... else of ia*/
  /* End of cleaning variable ia */
  } /*if (f2py_success) of drflai*/
  /* End of cleaning variable drflai */
  } /*if (f2py_success) of size_c*/
  /* End of cleaning variable size_c */
  /* End of cleaning variable fillic */
  /* End of cleaning variable ifillmax */
  } /*if (f2py_success) of msglvl*/
  /* End of cleaning variable msglvl */
  } /*if (f2py_success) of drflic*/
  /* End of cleaning variable drflic */
  /* End of cleaning variable garrow */
  /* End of cleaning variable droptyp */
  /* End of cleaning variable fillmax */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of rifsr ********************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_ainvsr2module_def[] = {
  {"ip",1,{{-1}},PyArray_INT},
  {"jp",1,{{-1}},PyArray_INT},
  {"ap",1,{{-1}},PyArray_DOUBLE},
  {"ainvsr2",-1,{{-1}},0,NULL,(void *)f2py_rout_sparslab_ainvsr2module_ainvsr2,doc_f2py_rout_sparslab_ainvsr2module_ainvsr2},
  {NULL}
};

static void f2py_setup_ainvsr2module(void (*ip)(int*,int*,void(*)(char*,int*),int*),void (*jp)(int*,int*,void(*)(char*,int*),int*),void (*ap)(int*,int*,void(*)(char*,int*),int*),char *ainvsr2) {
  int i_f2py=0;
  f2py_ainvsr2module_def[i_f2py++].func = ip;
  f2py_ainvsr2module_def[i_f2py++].func = jp;
  f2py_ainvsr2module_def[i_f2py++].func = ap;
  f2py_ainvsr2module_def[i_f2py++].data = ainvsr2;
}
extern void F_FUNC(f2pyinitainvsr2module,F2PYINITAINVSR2MODULE)(void (*)(void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char *));
static void f2py_init_ainvsr2module(void) {
  F_FUNC(f2pyinitainvsr2module,F2PYINITAINVSR2MODULE)(f2py_setup_ainvsr2module);
}


static FortranDataDef f2py_rifsrmodule_def[] = {
  {"ip",1,{{-1}},PyArray_INT},
  {"jp",1,{{-1}},PyArray_INT},
  {"ap",1,{{-1}},PyArray_DOUBLE},
  {"rifsr",-1,{{-1}},0,NULL,(void *)f2py_rout_sparslab_rifsrmodule_rifsr,doc_f2py_rout_sparslab_rifsrmodule_rifsr},
  {NULL}
};

static void f2py_setup_rifsrmodule(void (*ip)(int*,int*,void(*)(char*,int*),int*),void (*jp)(int*,int*,void(*)(char*,int*),int*),void (*ap)(int*,int*,void(*)(char*,int*),int*),char *rifsr) {
  int i_f2py=0;
  f2py_rifsrmodule_def[i_f2py++].func = ip;
  f2py_rifsrmodule_def[i_f2py++].func = jp;
  f2py_rifsrmodule_def[i_f2py++].func = ap;
  f2py_rifsrmodule_def[i_f2py++].data = rifsr;
}
extern void F_FUNC(f2pyinitrifsrmodule,F2PYINITRIFSRMODULE)(void (*)(void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),void (*)(int*,int*,void(*)(char*,int*),int*),char *));
static void f2py_init_rifsrmodule(void) {
  F_FUNC(f2pyinitrifsrmodule,F2PYINITRIFSRMODULE)(f2py_setup_rifsrmodule);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

PyMODINIT_FUNC initsparslab(void) {
  int i;
  PyObject *m,*d, *s;
  m = sparslab_module = Py_InitModule("sparslab", f2py_module_methods);
  PyFortran_Type.ob_type = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module sparslab (failed to import numpy)"); return;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
  s = PyString_FromString("This module 'sparslab' is auto-generated with f2py (version:2_5237).\nFunctions:\n"
"Fortran 90/95 modules:\n""  ainvsr2module --- ip,jp,ap,ainvsr2()""  rifsrmodule --- ip,jp,ap,rifsr()"".");
  PyDict_SetItemString(d, "__doc__", s);
  sparslab_error = PyErr_NewException ("sparslab.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));


/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "rifsrmodule", PyFortranObject_New(f2py_rifsrmodule_def,f2py_init_rifsrmodule));
  PyDict_SetItemString(d, "ainvsr2module", PyFortranObject_New(f2py_ainvsr2module_def,f2py_init_ainvsr2module));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"sparslab");
#endif

}
#ifdef __cplusplus
}
#endif
