!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2_5237)
!     It contains Fortran 90 wrappers to fortran functions.

      subroutine f2py_ainvsr2module_getdims_ip(r,s,f2pysetdata,flag)
      use ainvsr2module, only: d => ip

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_ainvsr2module_getdims_ip
      subroutine f2py_ainvsr2module_getdims_jp(r,s,f2pysetdata,flag)
      use ainvsr2module, only: d => jp

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_ainvsr2module_getdims_jp
      subroutine f2py_ainvsr2module_getdims_ap(r,s,f2pysetdata,flag)
      use ainvsr2module, only: d => ap

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_ainvsr2module_getdims_ap
      
      subroutine f2pyinitainvsr2module(f2pysetupfunc)
      use ainvsr2module, only : ip
      use ainvsr2module, only : jp
      use ainvsr2module, only : ap
      use ainvsr2module, only : ainvsr2
      external f2pysetupfunc
      external f2py_ainvsr2module_getdims_ip
      external f2py_ainvsr2module_getdims_jp
      external f2py_ainvsr2module_getdims_ap
      call f2pysetupfunc(f2py_ainvsr2module_getdims_ip,f2py_ainvsr2modul&
     &e_getdims_jp,f2py_ainvsr2module_getdims_ap,ainvsr2)
      end subroutine f2pyinitainvsr2module

      subroutine f2py_rifsrmodule_getdims_ip(r,s,f2pysetdata,flag)
      use rifsrmodule, only: d => ip

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_rifsrmodule_getdims_ip
      subroutine f2py_rifsrmodule_getdims_jp(r,s,f2pysetdata,flag)
      use rifsrmodule, only: d => jp

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_rifsrmodule_getdims_jp
      subroutine f2py_rifsrmodule_getdims_ap(r,s,f2pysetdata,flag)
      use rifsrmodule, only: d => ap

      integer flag
      external f2pysetdata
      logical ns
      integer r,i,j
      integer(8) s(*)
      ns = .FALSE.
      if (allocated(d)) then
         do i=1,r
            if ((size(d,i).ne.s(i)).and.(s(i).ge.0)) then
               ns = .TRUE.
            end if
         end do
         if (ns) then
            deallocate(d)
         end if
      end if
      if ((.not.allocated(d)).and.(s(1).ge.1)) then
       allocate(d(s(1)))
      end if
      if (allocated(d)) then
         do i=1,r
            s(i) = size(d,i)
         end do
      end if
      flag = 1
      call f2pysetdata(d,allocated(d))
      end subroutine f2py_rifsrmodule_getdims_ap
      
      subroutine f2pyinitrifsrmodule(f2pysetupfunc)
      use rifsrmodule, only : ip
      use rifsrmodule, only : jp
      use rifsrmodule, only : ap
      use rifsrmodule, only : rifsr
      external f2pysetupfunc
      external f2py_rifsrmodule_getdims_ip
      external f2py_rifsrmodule_getdims_jp
      external f2py_rifsrmodule_getdims_ap
      call f2pysetupfunc(f2py_rifsrmodule_getdims_ip,f2py_rifsrmodule_ge&
     &tdims_jp,f2py_rifsrmodule_getdims_ap,rifsr)
      end subroutine f2pyinitrifsrmodule


